/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.studentInfo.xbemy;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2008
 * 
 * XDoclet definition:
 * @struts.form name="xbemyStudentInfoForm"
 */
public class XbemyStudentInfoForm extends ActionForm {	
	
	//FormFile uploadFile;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6476757693457087728L;
	private FormFile file;
	private FormFile file1;
	private String xh;
	private String nj;
	private String xm;
	private String xb="男";
	private String xydm;
	private String zydm;
	private String bjdm;
	private String xymc;
	private String bjmc;
	private String mzmc;//民族名称
	private String zzmm;//政治面貌
	private String mzdm;//民族代码
	private String syd;//生源地
	private String daqk;//档案情况
	private String bz;//备注
	private String pqdwmc;//派遣单位名称
	private String ffsj;//发放时间
	private String pqzbh;//派遣证编号
	private String qdrxm;//取档人姓名
	private String ddqkdm;//到档情况代码
	
	/*******学籍异动申请转学*******/
	private String dyym;//对应页面
	private String zxlx;//转学类型 --转入 ---转出
	private String xz;//学制
	private String xjztm;//学籍状态码
	private String cym;//曾用名
	private String zyfx;//专业方向
	private String pyfx;//培养方向
	private String xxszd;//学校所在地
	private String dqszj;//当前所在级
	private String zylb;//专业类别
	private String fxzy;//辅修专业
	private String fxzyfx;//辅修专业方向
	private String bxlx;//办学类型
	private String bxxs;//办学形式
	private String xxxs;//学习形式
	private String zsjj;//招生季节
	private String pycc;//培养层次
	private String ksh;//考生号
	private String rxfs;//入学方式
	private String sfzh;//身份证号
	private String mz;//民族
	private String jg;//籍贯
	private String csd;//出生地
	private String csrq;//出生日期
	private String xzxm;//校长姓名
	private String byrq;//毕业日期
	private String bjyjl;//毕结业结论
	private String zsbh;//证书编号
	private String zsxlh;//证书序列号
	private String xw;//学位
	private String xwzsbh;//学位证书编号
	private String xwzsxlh;//学位证书序列号
	private String thbs;//替换标识
	private String shbj;//审核标记
	private String dybj;//打印标记
	private String sqrq;//申请日期
	private String rxsj;//入学时间
	private String zkzh;//准考证号
	private String lxdh;//联系电话
	private String zcxxmc;//转出学校名称
	private String zczymc;//转出专业名称
	private String zcnj;//转出年级
	private String zcxz;//转出学制
	private String zcxlcc;//转出学历层次
	private String zrxxmc;//转入学校名称
	private String zrzymc;//转入专业名称
	private String zrnj;//转入年级
	private String zrxz;//转入学制
	private String zrxlcc;//转入学历层次
	private String sqly;//申请理由
	private String zcxxyj;//转出学校意见
	private String zrxxyj;//转入学校意见
	private String zcsjytyj;//转出省教育厅意见
	private String zrsjytyj;//转入省教育厅意见
	private String xxsh;//学校审核
	private String zrxydm;//转入学院代码
	private String zrxymc;//转入学院名称
	private String zrbjdm;//转入班级代码
	private String zrbjmc;//转入班级名称
	//转出学生信息
	private String zcxydm;//转出学院代码
	private String zczydm;//转出专业代码
	private String zcbjdm;//转出班级代码
	private String zdzrbj="0";//自动转入标记
	/********学籍异动申请转专业*******/
	private String lqzydm;//录取专业代码
	private String zrzydm;//转入专业代码
	private String zczyyxyj;//转出专业学院意见
	private String zrzyyxyj;//转入学院专业意见
	private String zjcyj;//招就处意见
	private String cwcyj;//财务处意见
	private String xscyj;//学生处意见
	private String jwcyj;//教务处意见
	private String gdxxspyj;//高等学校审批意见
	private String zzqjytbayj;//自治区教育厅备案意见
	private String zczyxysh;//转出专业学院审核
	private String zrzyxysh;//转入专业学院审核
	private String zjcsh;//招就处审核
	private String cwcsh;//财务处审核
	private String jwcsh;//教务处审核
	private String xscsh;//学生处审核
	/*********学籍变动**********/
	private String qssj;//起始时间
	private String jzsj;//截止时间
	private String ydlbdm;//异动类别代码
	private String jtdz;//家庭地址
	private String jtdh;//家庭电话
	private String ydqnj;//异动前年级
	private String ydqzydm;//异动前专业代码
	private String ydqbjdm;//异动前班级代码
	private String ydhnj;//异动后年级
	private String ydhzydm;//异动后专业代码
	private String ydhbjdm;//异动后班级代码
	private String sqsj;//申请时间
	private String hqcsh;//后勤处审核
	private String hqcyj;//后勤处意见
	private String xldsh;//校领导审核
	private String xldyj;//校领导意见
	private String xsszysh;//学生所在院审核
	private String xsszyyj;//学生所在院意见
	
	
	public String getHqcsh() {
		return hqcsh;
	}
	public void setHqcsh(String hqcsh) {
		this.hqcsh = hqcsh;
	}
	public String getHqcyj() {
		return hqcyj;
	}
	public void setHqcyj(String hqcyj) {
		this.hqcyj = hqcyj;
	}
	public String getXldsh() {
		return xldsh;
	}
	public void setXldsh(String xldsh) {
		this.xldsh = xldsh;
	}
	public String getXldyj() {
		return xldyj;
	}
	public void setXldyj(String xldyj) {
		this.xldyj = xldyj;
	}
	public String getSqsj() {
		return sqsj;
	}
	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}
	public String getCwcsh() {
		return cwcsh;
	}
	public void setCwcsh(String cwcsh) {
		this.cwcsh = cwcsh;
	}
	public String getCwcyj() {
		return cwcyj;
	}
	public void setCwcyj(String cwcyj) {
		this.cwcyj = cwcyj;
	}
	public String getGdxxspyj() {
		return gdxxspyj;
	}
	public void setGdxxspyj(String gdxxspyj) {
		this.gdxxspyj = gdxxspyj;
	}
	public String getJwcsh() {
		return jwcsh;
	}
	public void setJwcsh(String jwcsh) {
		this.jwcsh = jwcsh;
	}
	public String getLqzydm() {
		return lqzydm;
	}
	public void setLqzydm(String lqzydm) {
		this.lqzydm = lqzydm;
	}
	public String getXscsh() {
		return xscsh;
	}
	public void setXscsh(String xscsh) {
		this.xscsh = xscsh;
	}
	public String getXscyj() {
		return xscyj;
	}
	public void setXscyj(String xscyj) {
		this.xscyj = xscyj;
	}
	public String getZczyxysh() {
		return zczyxysh;
	}
	public void setZczyxysh(String zczyxysh) {
		this.zczyxysh = zczyxysh;
	}
	public String getZczyyxyj() {
		return zczyyxyj;
	}
	public void setZczyyxyj(String zczyyxyj) {
		this.zczyyxyj = zczyyxyj;
	}
	public String getZrzyyxyj() {
		return zrzyyxyj;
	}
	public void setZrzyyxyj(String zrzyyxyj) {
		this.zrzyyxyj = zrzyyxyj;
	}
	public String getZjcsh() {
		return zjcsh;
	}
	public void setZjcsh(String zjcsh) {
		this.zjcsh = zjcsh;
	}
	public String getZjcyj() {
		return zjcyj;
	}
	public void setZjcyj(String zjcyj) {
		this.zjcyj = zjcyj;
	}
	public String getZrzyxysh() {
		return zrzyxysh;
	}
	public void setZrzyxysh(String zrzyxysh) {
		this.zrzyxysh = zrzyxysh;
	}
	public String getZzqjytbayj() {
		return zzqjytbayj;
	}
	public void setZzqjytbayj(String zzqjytbayj) {
		this.zzqjytbayj = zzqjytbayj;
	}
	public String getLxdh() {
		return lxdh;
	}
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}
	public String getRxsj() {
		return rxsj;
	}
	public void setRxsj(String rxsj) {
		this.rxsj = rxsj;
	}
	public String getSqly() {
		return sqly;
	}
	public void setSqly(String sqly) {
		this.sqly = sqly;
	}
	public String getSqrq() {
		return sqrq;
	}
	public void setSqrq(String sqrq) {
		this.sqrq = sqrq;
	}
	public String getXxsh() {
		return xxsh;
	}
	public void setXxsh(String xxsh) {
		this.xxsh = xxsh;
	}
	public String getZcnj() {
		return zcnj;
	}
	public void setZcnj(String zcnj) {
		this.zcnj = zcnj;
	}
	public String getZcsjytyj() {
		return zcsjytyj;
	}
	public void setZcsjytyj(String zcsjytyj) {
		this.zcsjytyj = zcsjytyj;
	}
	public String getZcxlcc() {
		return zcxlcc;
	}
	public void setZcxlcc(String zcxlcc) {
		this.zcxlcc = zcxlcc;
	}
	public String getZcxxmc() {
		return zcxxmc;
	}
	public void setZcxxmc(String zcxxmc) {
		this.zcxxmc = zcxxmc;
	}
	public String getZcxxyj() {
		return zcxxyj;
	}
	public void setZcxxyj(String zcxxyj) {
		this.zcxxyj = zcxxyj;
	}
	public String getZcxz() {
		return zcxz;
	}
	public void setZcxz(String zcxz) {
		this.zcxz = zcxz;
	}
	public String getZczymc() {
		return zczymc;
	}
	public void setZczymc(String zczymc) {
		this.zczymc = zczymc;
	}
	public String getZkzh() {
		return zkzh;
	}
	public void setZkzh(String zkzh) {
		this.zkzh = zkzh;
	}
	public String getZrnj() {
		return zrnj;
	}
	public void setZrnj(String zrnj) {
		this.zrnj = zrnj;
	}
	public String getZrsjytyj() {
		return zrsjytyj;
	}
	public void setZrsjytyj(String zrsjytyj) {
		this.zrsjytyj = zrsjytyj;
	}
	public String getZrxlcc() {
		return zrxlcc;
	}
	public void setZrxlcc(String zrxlcc) {
		this.zrxlcc = zrxlcc;
	}
	public String getZrxxmc() {
		return zrxxmc;
	}
	public void setZrxxmc(String zrxxmc) {
		this.zrxxmc = zrxxmc;
	}
	public String getZrxxyj() {
		return zrxxyj;
	}
	public void setZrxxyj(String zrxxyj) {
		this.zrxxyj = zrxxyj;
	}
	public String getZrxz() {
		return zrxz;
	}
	public void setZrxz(String zrxz) {
		this.zrxz = zrxz;
	}
	public String getZrzymc() {
		return zrzymc;
	}
	public void setZrzymc(String zrzymc) {
		this.zrzymc = zrzymc;
	}
	public String getQdrxm() {
		return qdrxm;
	}
	public void setQdrxm(String qdrxm) {
		this.qdrxm = qdrxm;
	}
	public String getFfsj() {
		return ffsj;
	}
	public void setFfsj(String ffsj) {
		this.ffsj = ffsj;
	}
	public String getPqdwmc() {
		return pqdwmc;
	}
	public void setPqdwmc(String pqdwmc) {
		this.pqdwmc = pqdwmc;
	}
	public String getPqzbh() {
		return pqzbh;
	}
	public void setPqzbh(String pqzbh) {
		this.pqzbh = pqzbh;
	}
	public String getBz() {
		return bz;
	}
	public void setBz(String bz) {
		this.bz = bz;
	}
	public String getBjdm() {
		return bjdm;
	}
	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}
	public String getBjmc() {
		return bjmc;
	}
	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}
	public String getNj() {
		return nj;
	}
	public void setNj(String nj) {
		this.nj = nj;
	}
	public String getXb() {
		return xb;
	}
	public void setXb(String xb) {
		this.xb = xb;
	}
	public String getXh() {
		return xh;
	}
	public void setXh(String xh) {
		this.xh = xh;
	}
	public String getXm() {
		return xm;
	}
	public void setXm(String xm) {
		this.xm = xm;
	}
	public String getXydm() {
		return xydm;
	}
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
	public String getXymc() {
		return xymc;
	}
	public void setXymc(String xymc) {
		this.xymc = xymc;
	}
	public String getZydm() {
		return zydm;
	}
	public void setZydm(String zydm) {
		this.zydm = zydm;
	}
	
	public String getMzdm() {
		return mzdm;
	}
	public void setMzdm(String mzdm) {
		this.mzdm = mzdm;
	}
	public String getMzmc() {
		return mzmc;
	}
	public void setMzmc(String mzmc) {
		this.mzmc = mzmc;
	}
	public String getSyd() {
		return syd;
	}
	public void setSyd(String syd) {
		this.syd = syd;
	}
	public String getDaqk() {
		return daqk;
	}
	public void setDaqk(String daqk) {
		this.daqk = daqk;
	}
	public String getZrzydm() {
		return zrzydm;
	}
	public void setZrzydm(String zrzydm) {
		this.zrzydm = zrzydm;
	}
	public String getJtdh() {
		return jtdh;
	}
	public void setJtdh(String jtdh) {
		this.jtdh = jtdh;
	}
	public String getJtdz() {
		return jtdz;
	}
	public void setJtdz(String jtdz) {
		this.jtdz = jtdz;
	}
	public String getJzsj() {
		return jzsj;
	}
	public void setJzsj(String jzsj) {
		this.jzsj = jzsj;
	}
	public String getQssj() {
		return qssj;
	}
	public void setQssj(String qssj) {
		this.qssj = qssj;
	}
	public String getYdhbjdm() {
		return ydhbjdm;
	}
	public void setYdhbjdm(String ydhbjdm) {
		this.ydhbjdm = ydhbjdm;
	}
	public String getYdhnj() {
		return ydhnj;
	}
	public void setYdhnj(String ydhnj) {
		this.ydhnj = ydhnj;
	}
	public String getYdhzydm() {
		return ydhzydm;
	}
	public void setYdhzydm(String ydhzydm) {
		this.ydhzydm = ydhzydm;
	}
	public String getYdlbdm() {
		return ydlbdm;
	}
	public void setYdlbdm(String ydlbdm) {
		this.ydlbdm = ydlbdm;
	}
	public String getYdqbjdm() {
		return ydqbjdm;
	}
	public void setYdqbjdm(String ydqbjdm) {
		this.ydqbjdm = ydqbjdm;
	}
	public String getYdqnj() {
		return ydqnj;
	}
	public void setYdqnj(String ydqnj) {
		this.ydqnj = ydqnj;
	}
	public String getYdqzydm() {
		return ydqzydm;
	}
	public void setYdqzydm(String ydqzydm) {
		this.ydqzydm = ydqzydm;
	}
	public String getJwcyj() {
		return jwcyj;
	}
	public void setJwcyj(String jwcyj) {
		this.jwcyj = jwcyj;
	}
	public String getXsszysh() {
		return xsszysh;
	}
	public void setXsszysh(String xsszysh) {
		this.xsszysh = xsszysh;
	}
	public String getXsszyyj() {
		return xsszyyj;
	}
	public void setXsszyyj(String xsszyyj) {
		this.xsszyyj = xsszyyj;
	}
	
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public FormFile getFile1() {
		return file1;
	}
	public void setFile1(FormFile file1) {
		this.file1 = file1;
	}
	public String getDdqkdm() {
		return ddqkdm;
	}
	public void setDdqkdm(String ddqkdm) {
		this.ddqkdm = ddqkdm;
	}
	public String getBjyjl() {
		return bjyjl;
	}
	public void setBjyjl(String bjyjl) {
		this.bjyjl = bjyjl;
	}
	public String getBxlx() {
		return bxlx;
	}
	public void setBxlx(String bxlx) {
		this.bxlx = bxlx;
	}
	public String getBxxs() {
		return bxxs;
	}
	public void setBxxs(String bxxs) {
		this.bxxs = bxxs;
	}
	public String getByrq() {
		return byrq;
	}
	public void setByrq(String byrq) {
		this.byrq = byrq;
	}
	public String getCsd() {
		return csd;
	}
	public void setCsd(String csd) {
		this.csd = csd;
	}
	public String getCsrq() {
		return csrq;
	}
	public void setCsrq(String csrq) {
		this.csrq = csrq;
	}
	public String getCym() {
		return cym;
	}
	public void setCym(String cym) {
		this.cym = cym;
	}
	public String getDqszj() {
		return dqszj;
	}
	public void setDqszj(String dqszj) {
		this.dqszj = dqszj;
	}
	public String getDybj() {
		return dybj;
	}
	public void setDybj(String dybj) {
		this.dybj = dybj;
	}
	public String getDyym() {
		return dyym;
	}
	public void setDyym(String dyym) {
		this.dyym = dyym;
	}
	public String getFxzy() {
		return fxzy;
	}
	public void setFxzy(String fxzy) {
		this.fxzy = fxzy;
	}
	public String getFxzyfx() {
		return fxzyfx;
	}
	public void setFxzyfx(String fxzyfx) {
		this.fxzyfx = fxzyfx;
	}
	public String getJg() {
		return jg;
	}
	public void setJg(String jg) {
		this.jg = jg;
	}
	public String getKsh() {
		return ksh;
	}
	public void setKsh(String ksh) {
		this.ksh = ksh;
	}
	public String getMz() {
		return mz;
	}
	public void setMz(String mz) {
		this.mz = mz;
	}
	public String getPycc() {
		return pycc;
	}
	public void setPycc(String pycc) {
		this.pycc = pycc;
	}
	public String getPyfx() {
		return pyfx;
	}
	public void setPyfx(String pyfx) {
		this.pyfx = pyfx;
	}
	public String getRxfs() {
		return rxfs;
	}
	public void setRxfs(String rxfs) {
		this.rxfs = rxfs;
	}
	public String getSfzh() {
		return sfzh;
	}
	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}
	public String getShbj() {
		return shbj;
	}
	public void setShbj(String shbj) {
		this.shbj = shbj;
	}
	public String getThbs() {
		return thbs;
	}
	public void setThbs(String thbs) {
		this.thbs = thbs;
	}
	public String getXjztm() {
		return xjztm;
	}
	public void setXjztm(String xjztm) {
		this.xjztm = xjztm;
	}
	public String getXw() {
		return xw;
	}
	public void setXw(String xw) {
		this.xw = xw;
	}
	public String getXwzsbh() {
		return xwzsbh;
	}
	public void setXwzsbh(String xwzsbh) {
		this.xwzsbh = xwzsbh;
	}
	public String getXwzsxlh() {
		return xwzsxlh;
	}
	public void setXwzsxlh(String xwzsxlh) {
		this.xwzsxlh = xwzsxlh;
	}
	public String getXxszd() {
		return xxszd;
	}
	public void setXxszd(String xxszd) {
		this.xxszd = xxszd;
	}
	public String getXxxs() {
		return xxxs;
	}
	public void setXxxs(String xxxs) {
		this.xxxs = xxxs;
	}
	public String getXz() {
		return xz;
	}
	public void setXz(String xz) {
		this.xz = xz;
	}
	public String getXzxm() {
		return xzxm;
	}
	public void setXzxm(String xzxm) {
		this.xzxm = xzxm;
	}
	public String getZsbh() {
		return zsbh;
	}
	public void setZsbh(String zsbh) {
		this.zsbh = zsbh;
	}
	public String getZsjj() {
		return zsjj;
	}
	public void setZsjj(String zsjj) {
		this.zsjj = zsjj;
	}	
	public String getZxlx() {
		return zxlx;
	}
	public void setZxlx(String zxlx) {
		this.zxlx = zxlx;
	}
	public String getZyfx() {
		return zyfx;
	}
	public void setZyfx(String zyfx) {
		this.zyfx = zyfx;
	}
	public String getZylb() {
		return zylb;
	}
	public void setZylb(String zylb) {
		this.zylb = zylb;
	}
	public String getZrbjdm() {
		return zrbjdm;
	}
	public void setZrbjdm(String zrbjdm) {
		this.zrbjdm = zrbjdm;
	}
	public String getZrbjmc() {
		return zrbjmc;
	}
	public void setZrbjmc(String zrbjmc) {
		this.zrbjmc = zrbjmc;
	}
	public String getZrxydm() {
		return zrxydm;
	}
	public void setZrxydm(String zrxydm) {
		this.zrxydm = zrxydm;
	}
	public String getZrxymc() {
		return zrxymc;
	}
	public void setZrxymc(String zrxymc) {
		this.zrxymc = zrxymc;
	}
	public String getZsxlh() {
		return zsxlh;
	}
	public void setZsxlh(String zsxlh) {
		this.zsxlh = zsxlh;
	}
	public String getZcbjdm() {
		return zcbjdm;
	}
	public void setZcbjdm(String zcbjdm) {
		this.zcbjdm = zcbjdm;
	}
	public String getZcxydm() {
		return zcxydm;
	}
	public void setZcxydm(String zcxydm) {
		this.zcxydm = zcxydm;
	}
	public String getZczydm() {
		return zczydm;
	}
	public void setZczydm(String zczydm) {
		this.zczydm = zczydm;
	}
	public String getZdzrbj() {
		return zdzrbj;
	}
	public void setZdzrbj(String zdzrbj) {
		this.zdzrbj = zdzrbj;
	}
	public String getZzmm() {
		return zzmm;
	}
	public void setZzmm(String zzmm) {
		this.zzmm = zzmm;
	}
}