/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xsgygl.ynys.qsz;

import org.apache.struts.action.ActionForm;

import xgxt.utils.Pages;

/** 
 * MyEclipse Struts
 * Creation date: 09-06-2010
 * 
 * XDoclet definition:
 * @struts.form name="ynysQszForm"
 */
public class YnysQszForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	private String []primarykey_cbv;
	private String []checkVal;

	
	private String dsjssf;     //收视费
	private String nj;     //年级
	private String jtdh;     //家庭电话
	private String pycc;     //培养层次
	private String jzrq;     //退房时间
	private String zydm;     //专业代码
	private String mz;     //民族
	private String sfbz;     //收费标准
	private String lxdh;     //联系电话
	private String jtdz;     //家庭地址
	private String sydmc;     //生源地名称
	private String xh;     //学号
	private String xm;     //姓名
	private String zymc;     //专业名称
	private String bz;     //备注
	private String sjhm;     //手机号码
	private String sfzh;     //身份证号
	private String qsdh;     //寝室电话
	private String xqmc;     //校区名称
	private String zsf;     //住宿费
	private String xydm;     //院系代码
	private String bjdm;     //班级代码
	private String jg;     //籍贯
	private String zzmmmc;     //政治面貌
	private String cwh;     //床位号
	private String cws;     //床位数
	private String cs;     //楼层
	private String fpbj;     //分配标记
	private String gyqk;     //公寓情况
	private String zzmm;     //政治面貌代码
	private String lddm;     //楼栋代码
	private String ldmc;     //楼栋名称
	private String qsh;     //寝室号
	private String xqdm;     //校区代码
	private String yqdm;     //园区代码
	private String yqmc;     //园区名称
	private String ssbh;     //宿舍编号
	private String sfqsz;     //是否寝室长
	private String rzrq;     //入住日期
	private String xb;     //性别
	private String xymc;     //院系名称
	private String bjmc;     //班级名称
	
	private String querylike_xh;
	private String querylike_xm;
	private String queryequals_cws;     //床位数
	private String queryequals_gyqk;     //公寓情况
	private String queryequals_sfbz;     //收费标准
	private String queryequals_sfqsz;     //是否寝室长
	private String queryequals_jzrq;     //退房时间
	private String queryequals_fpbj;     //分配标记
	private String queryequals_xqdm;     //校区代码
	private String queryequals_yqdm;     //园区代码
	private String queryequals_yqmc;     //园区名称
	private String queryequals_zzmm;     //政治面貌代码
	private String queryequals_zzmmmc;     //政治面貌
	private String queryequals_sjhm;     //手机号码
	private String queryequals_jtdz;     //家庭地址
	private String queryequals_ldmc;     //楼栋名称
	private String queryequals_xydm;     //院系代码
	private String queryequals_mz;     //民族
	private String queryequals_cwh;     //床位号
	private String queryequals_zsf;     //住宿费
	private String queryequals_bjdm;     //班级代码
	private String queryequals_bjmc;     //班级名称
	private String queryequals_pycc;     //培养层次
	private String queryequals_sfzh;     //身份证号
	private String queryequals_zymc;     //专业名称
	private String queryequals_lxdh;     //联系电话
	private String queryequals_rzrq;     //入住日期
	private String queryequals_jg;     //籍贯
	private String queryequals_xh;     //学号
	private String queryequals_qsh;     //寝室号
	private String queryequals_qsdh;     //寝室电话
	private String queryequals_xqmc;     //校区名称
	private String queryequals_dsjssf;     //收视费
	private String queryequals_xb;     //性别
	private String queryequals_zydm;     //专业代码
	private String queryequals_sydmc;     //生源地名称
	private String queryequals_ssbh;     //宿舍编号
	private String queryequals_lddm;     //楼栋代码
	private String queryequals_cs;     //楼层
	private String queryequals_xm;     //姓名
	private String queryequals_nj;     //年级
	private String queryequals_xymc;     //院系名称
	private String queryequals_bz;     //备注
	private String queryequals_jtdh;     //家庭电话
	
	private Pages pages=new Pages();
	public Pages getPages() {
		return pages;
	}
	public void setPages(Pages pages) {
		this.pages = pages;
	}
	
	public String getQueryequals_cs() {
		return queryequals_cs;
	}
	public void setQueryequals_cs(String queryequals_cs) {
		this.queryequals_cs = queryequals_cs;
	}
	public String getQueryequals_lddm() {
		return queryequals_lddm;
	}
	public void setQueryequals_lddm(String queryequals_lddm) {
		this.queryequals_lddm = queryequals_lddm;
	}
	public String getQueryequals_qsh() {
		return queryequals_qsh;
	}
	public void setQueryequals_qsh(String queryequals_qsh) {
		this.queryequals_qsh = queryequals_qsh;
	}
	public String getQueryequals_xqdm() {
		return queryequals_xqdm;
	}
	public void setQueryequals_xqdm(String queryequals_xqdm) {
		this.queryequals_xqdm = queryequals_xqdm;
	}
	public String[] getPrimarykey_cbv() {
		return primarykey_cbv;
	}
	public void setPrimarykey_cbv(String[] primarykey_cbv) {
		this.primarykey_cbv = primarykey_cbv;
	}
	public String[] getCheckVal() {
		return checkVal;
	}
	public void setCheckVal(String[] checkVal) {
		this.checkVal = checkVal;
	}
	public String getBjdm() {
		return bjdm;
	}
	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}
	public String getBjmc() {
		return bjmc;
	}
	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}
	public String getBz() {
		return bz;
	}
	public void setBz(String bz) {
		this.bz = bz;
	}
	public String getCs() {
		return cs;
	}
	public void setCs(String cs) {
		this.cs = cs;
	}
	public String getCwh() {
		return cwh;
	}
	public void setCwh(String cwh) {
		this.cwh = cwh;
	}
	public String getCws() {
		return cws;
	}
	public void setCws(String cws) {
		this.cws = cws;
	}
	public String getDsjssf() {
		return dsjssf;
	}
	public void setDsjssf(String dsjssf) {
		this.dsjssf = dsjssf;
	}
	public String getFpbj() {
		return fpbj;
	}
	public void setFpbj(String fpbj) {
		this.fpbj = fpbj;
	}
	public String getGyqk() {
		return gyqk;
	}
	public void setGyqk(String gyqk) {
		this.gyqk = gyqk;
	}
	public String getJg() {
		return jg;
	}
	public void setJg(String jg) {
		this.jg = jg;
	}
	public String getJtdh() {
		return jtdh;
	}
	public void setJtdh(String jtdh) {
		this.jtdh = jtdh;
	}
	public String getJtdz() {
		return jtdz;
	}
	public void setJtdz(String jtdz) {
		this.jtdz = jtdz;
	}
	public String getJzrq() {
		return jzrq;
	}
	public void setJzrq(String jzrq) {
		this.jzrq = jzrq;
	}
	public String getLddm() {
		return lddm;
	}
	public void setLddm(String lddm) {
		this.lddm = lddm;
	}
	public String getLdmc() {
		return ldmc;
	}
	public void setLdmc(String ldmc) {
		this.ldmc = ldmc;
	}
	public String getLxdh() {
		return lxdh;
	}
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}
	public String getMz() {
		return mz;
	}
	public void setMz(String mz) {
		this.mz = mz;
	}
	public String getNj() {
		return nj;
	}
	public void setNj(String nj) {
		this.nj = nj;
	}
	public String getPycc() {
		return pycc;
	}
	public void setPycc(String pycc) {
		this.pycc = pycc;
	}
	public String getQsdh() {
		return qsdh;
	}
	public void setQsdh(String qsdh) {
		this.qsdh = qsdh;
	}
	public String getQsh() {
		return qsh;
	}
	public void setQsh(String qsh) {
		this.qsh = qsh;
	}
	public String getQueryequals_bjdm() {
		return queryequals_bjdm;
	}
	public void setQueryequals_bjdm(String queryequals_bjdm) {
		this.queryequals_bjdm = queryequals_bjdm;
	}
	public String getQueryequals_bjmc() {
		return queryequals_bjmc;
	}
	public void setQueryequals_bjmc(String queryequals_bjmc) {
		this.queryequals_bjmc = queryequals_bjmc;
	}
	public String getQueryequals_bz() {
		return queryequals_bz;
	}
	public void setQueryequals_bz(String queryequals_bz) {
		this.queryequals_bz = queryequals_bz;
	}
	public String getQueryequals_cwh() {
		return queryequals_cwh;
	}
	public void setQueryequals_cwh(String queryequals_cwh) {
		this.queryequals_cwh = queryequals_cwh;
	}
	public String getQueryequals_cws() {
		return queryequals_cws;
	}
	public void setQueryequals_cws(String queryequals_cws) {
		this.queryequals_cws = queryequals_cws;
	}
	public String getQueryequals_dsjssf() {
		return queryequals_dsjssf;
	}
	public void setQueryequals_dsjssf(String queryequals_dsjssf) {
		this.queryequals_dsjssf = queryequals_dsjssf;
	}
	public String getQueryequals_fpbj() {
		return queryequals_fpbj;
	}
	public void setQueryequals_fpbj(String queryequals_fpbj) {
		this.queryequals_fpbj = queryequals_fpbj;
	}
	public String getQueryequals_gyqk() {
		return queryequals_gyqk;
	}
	public void setQueryequals_gyqk(String queryequals_gyqk) {
		this.queryequals_gyqk = queryequals_gyqk;
	}
	public String getQueryequals_jg() {
		return queryequals_jg;
	}
	public void setQueryequals_jg(String queryequals_jg) {
		this.queryequals_jg = queryequals_jg;
	}
	public String getQueryequals_jtdh() {
		return queryequals_jtdh;
	}
	public void setQueryequals_jtdh(String queryequals_jtdh) {
		this.queryequals_jtdh = queryequals_jtdh;
	}
	public String getQueryequals_jtdz() {
		return queryequals_jtdz;
	}
	public void setQueryequals_jtdz(String queryequals_jtdz) {
		this.queryequals_jtdz = queryequals_jtdz;
	}
	public String getQueryequals_jzrq() {
		return queryequals_jzrq;
	}
	public void setQueryequals_jzrq(String queryequals_jzrq) {
		this.queryequals_jzrq = queryequals_jzrq;
	}
	public String getQueryequals_ldmc() {
		return queryequals_ldmc;
	}
	public void setQueryequals_ldmc(String queryequals_ldmc) {
		this.queryequals_ldmc = queryequals_ldmc;
	}
	public String getQueryequals_lxdh() {
		return queryequals_lxdh;
	}
	public void setQueryequals_lxdh(String queryequals_lxdh) {
		this.queryequals_lxdh = queryequals_lxdh;
	}
	public String getQueryequals_mz() {
		return queryequals_mz;
	}
	public void setQueryequals_mz(String queryequals_mz) {
		this.queryequals_mz = queryequals_mz;
	}
	public String getQueryequals_nj() {
		return queryequals_nj;
	}
	public void setQueryequals_nj(String queryequals_nj) {
		this.queryequals_nj = queryequals_nj;
	}
	public String getQueryequals_pycc() {
		return queryequals_pycc;
	}
	public void setQueryequals_pycc(String queryequals_pycc) {
		this.queryequals_pycc = queryequals_pycc;
	}
	public String getQueryequals_qsdh() {
		return queryequals_qsdh;
	}
	public void setQueryequals_qsdh(String queryequals_qsdh) {
		this.queryequals_qsdh = queryequals_qsdh;
	}
	public String getQueryequals_rzrq() {
		return queryequals_rzrq;
	}
	public void setQueryequals_rzrq(String queryequals_rzrq) {
		this.queryequals_rzrq = queryequals_rzrq;
	}
	public String getQueryequals_sfbz() {
		return queryequals_sfbz;
	}
	public void setQueryequals_sfbz(String queryequals_sfbz) {
		this.queryequals_sfbz = queryequals_sfbz;
	}
	public String getQueryequals_sfqsz() {
		return queryequals_sfqsz;
	}
	public void setQueryequals_sfqsz(String queryequals_sfqsz) {
		this.queryequals_sfqsz = queryequals_sfqsz;
	}
	public String getQueryequals_sfzh() {
		return queryequals_sfzh;
	}
	public void setQueryequals_sfzh(String queryequals_sfzh) {
		this.queryequals_sfzh = queryequals_sfzh;
	}
	public String getQueryequals_sjhm() {
		return queryequals_sjhm;
	}
	public void setQueryequals_sjhm(String queryequals_sjhm) {
		this.queryequals_sjhm = queryequals_sjhm;
	}
	public String getQueryequals_ssbh() {
		return queryequals_ssbh;
	}
	public void setQueryequals_ssbh(String queryequals_ssbh) {
		this.queryequals_ssbh = queryequals_ssbh;
	}
	public String getQueryequals_sydmc() {
		return queryequals_sydmc;
	}
	public void setQueryequals_sydmc(String queryequals_sydmc) {
		this.queryequals_sydmc = queryequals_sydmc;
	}
	public String getQueryequals_xb() {
		return queryequals_xb;
	}
	public void setQueryequals_xb(String queryequals_xb) {
		this.queryequals_xb = queryequals_xb;
	}
	public String getQueryequals_xh() {
		return queryequals_xh;
	}
	public void setQueryequals_xh(String queryequals_xh) {
		this.queryequals_xh = queryequals_xh;
	}
	public String getQueryequals_xm() {
		return queryequals_xm;
	}
	public void setQueryequals_xm(String queryequals_xm) {
		this.queryequals_xm = queryequals_xm;
	}
	public String getQueryequals_xqmc() {
		return queryequals_xqmc;
	}
	public void setQueryequals_xqmc(String queryequals_xqmc) {
		this.queryequals_xqmc = queryequals_xqmc;
	}
	public String getQueryequals_xydm() {
		return queryequals_xydm;
	}
	public void setQueryequals_xydm(String queryequals_xydm) {
		this.queryequals_xydm = queryequals_xydm;
	}
	public String getQueryequals_xymc() {
		return queryequals_xymc;
	}
	public void setQueryequals_xymc(String queryequals_xymc) {
		this.queryequals_xymc = queryequals_xymc;
	}
	public String getQueryequals_yqdm() {
		return queryequals_yqdm;
	}
	public void setQueryequals_yqdm(String queryequals_yqdm) {
		this.queryequals_yqdm = queryequals_yqdm;
	}
	public String getQueryequals_yqmc() {
		return queryequals_yqmc;
	}
	public void setQueryequals_yqmc(String queryequals_yqmc) {
		this.queryequals_yqmc = queryequals_yqmc;
	}
	public String getQueryequals_zsf() {
		return queryequals_zsf;
	}
	public void setQueryequals_zsf(String queryequals_zsf) {
		this.queryequals_zsf = queryequals_zsf;
	}
	public String getQueryequals_zydm() {
		return queryequals_zydm;
	}
	public void setQueryequals_zydm(String queryequals_zydm) {
		this.queryequals_zydm = queryequals_zydm;
	}
	public String getQueryequals_zymc() {
		return queryequals_zymc;
	}
	public void setQueryequals_zymc(String queryequals_zymc) {
		this.queryequals_zymc = queryequals_zymc;
	}
	public String getQueryequals_zzmm() {
		return queryequals_zzmm;
	}
	public void setQueryequals_zzmm(String queryequals_zzmm) {
		this.queryequals_zzmm = queryequals_zzmm;
	}
	public String getQueryequals_zzmmmc() {
		return queryequals_zzmmmc;
	}
	public void setQueryequals_zzmmmc(String queryequals_zzmmmc) {
		this.queryequals_zzmmmc = queryequals_zzmmmc;
	}
	public String getRzrq() {
		return rzrq;
	}
	public void setRzrq(String rzrq) {
		this.rzrq = rzrq;
	}
	public String getSfbz() {
		return sfbz;
	}
	public void setSfbz(String sfbz) {
		this.sfbz = sfbz;
	}
	public String getSfqsz() {
		return sfqsz;
	}
	public void setSfqsz(String sfqsz) {
		this.sfqsz = sfqsz;
	}
	public String getSfzh() {
		return sfzh;
	}
	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}
	public String getSjhm() {
		return sjhm;
	}
	public void setSjhm(String sjhm) {
		this.sjhm = sjhm;
	}
	public String getSsbh() {
		return ssbh;
	}
	public void setSsbh(String ssbh) {
		this.ssbh = ssbh;
	}
	public String getSydmc() {
		return sydmc;
	}
	public void setSydmc(String sydmc) {
		this.sydmc = sydmc;
	}
	public String getXb() {
		return xb;
	}
	public void setXb(String xb) {
		this.xb = xb;
	}
	public String getXh() {
		return xh;
	}
	public void setXh(String xh) {
		this.xh = xh;
	}
	public String getXm() {
		return xm;
	}
	public void setXm(String xm) {
		this.xm = xm;
	}
	public String getXqdm() {
		return xqdm;
	}
	public void setXqdm(String xqdm) {
		this.xqdm = xqdm;
	}
	public String getXqmc() {
		return xqmc;
	}
	public void setXqmc(String xqmc) {
		this.xqmc = xqmc;
	}
	public String getXydm() {
		return xydm;
	}
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
	public String getXymc() {
		return xymc;
	}
	public void setXymc(String xymc) {
		this.xymc = xymc;
	}
	public String getYqdm() {
		return yqdm;
	}
	public void setYqdm(String yqdm) {
		this.yqdm = yqdm;
	}
	public String getYqmc() {
		return yqmc;
	}
	public void setYqmc(String yqmc) {
		this.yqmc = yqmc;
	}
	public String getZsf() {
		return zsf;
	}
	public void setZsf(String zsf) {
		this.zsf = zsf;
	}
	public String getZydm() {
		return zydm;
	}
	public void setZydm(String zydm) {
		this.zydm = zydm;
	}
	public String getZymc() {
		return zymc;
	}
	public void setZymc(String zymc) {
		this.zymc = zymc;
	}
	public String getZzmm() {
		return zzmm;
	}
	public void setZzmm(String zzmm) {
		this.zzmm = zzmm;
	}
	public String getZzmmmc() {
		return zzmmmc;
	}
	public void setZzmmmc(String zzmmmc) {
		this.zzmmmc = zzmmmc;
	}
	public String getQuerylike_xh() {
		return querylike_xh;
	}
	public void setQuerylike_xh(String querylike_xh) {
		this.querylike_xh = querylike_xh;
	}
	public String getQuerylike_xm() {
		return querylike_xm;
	}
	public void setQuerylike_xm(String querylike_xm) {
		this.querylike_xm = querylike_xm;
	}
	
}