/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xsgygl.ghxy.qyfdywh;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import xgxt.utils.Pages;

/** 
 * MyEclipse Struts
 * Creation date: 08-05-2010
 * 
 * XDoclet definition:
 * @struts.form name="ghxyQyfdywhForm"
 */
public class GhxyQyfdywhForm extends ActionForm {
	private String []xqqdm;
	private String []CheckVal;
	private String []zgh;
	private String []yqqdm;
	private String yqdm;
	private String []primarykey_cbv;
	
	private String querylike_zgh;
	private String querylike_zwmc;
	private String queryequals_yqqdm;
	private String querylike_xm;
	private String queryequals_bmdm;
	
	private Pages pages=new Pages();
	public Pages getPages() {
		return pages;
	}
	public void setPages(Pages pages) {
		this.pages = pages;
	}

	public String getQueryequals_bmdm() {
		return queryequals_bmdm;
	}
	public void setQueryequals_bmdm(String queryequals_bmdm) {
		this.queryequals_bmdm = queryequals_bmdm;
	}
	
	public String[] getCheckVal() {
		return CheckVal;
	}
	public void setCheckVal(String[] checkVal) {
		CheckVal = checkVal;
	}
	public void setZgh(String[] zgh) {
		this.zgh = zgh;
	}
	public String[] getZgh() {
		return zgh;
	}
	public String[] getXqqdm() {
		return xqqdm;
	}
	public void setXqqdm(String[] xqqdm) {
		this.xqqdm = xqqdm;
	}
	public String[] getYqqdm() {
		return yqqdm;
	}
	public String getYqdm() {
		return yqdm;
	}
	public void setYqdm(String yqdm) {
		this.yqdm = yqdm;
	}
	public void setYqqdm(String[] yqqdm) {
		this.yqqdm = yqqdm;
	}
	public String getQueryequals_yqqdm() {
		return queryequals_yqqdm;
	}
	public void setQueryequals_yqqdm(String queryequals_yqqdm) {
		this.queryequals_yqqdm = queryequals_yqqdm;
	}
	public String getQuerylike_xm() {
		return querylike_xm;
	}
	public void setQuerylike_xm(String querylike_xm) {
		this.querylike_xm = querylike_xm;
	}
	public String[] getPrimarykey_cbv() {
		return primarykey_cbv;
	}
	public void setPrimarykey_cbv(String[] primarykey_cbv) {
		this.primarykey_cbv = primarykey_cbv;
	}
	public String getQuerylike_zgh() {
		return querylike_zgh;
	}
	public void setQuerylike_zgh(String querylike_zgh) {
		this.querylike_zgh = querylike_zgh;
	}
	public String getQuerylike_zwmc() {
		return querylike_zwmc;
	}
	public void setQuerylike_zwmc(String querylike_zwmc) {
		this.querylike_zwmc = querylike_zwmc;
	}
	

}

