/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.bxgl.ntzy.ylbx;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import xgxt.action.Base;
import xgxt.action.BaseAction;
import xgxt.studentInfo.service.XsxxglService;
import xgxt.utils.FormModleCommon;
import xgxt.utils.GetTime;

/** 
 * MyEclipse Struts
 * Creation date: 10-18-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class NtzyYlbxAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	protected static final String QUERY = "qry";//页面查询操作判断标志
	
	protected static final String DELETE = "del";//页面删除操作判断标志
	
	protected static final String VIEW = "view";//页面单个显示详细操作判断标志
	
	protected static final String MODIFY = "modi";//页面修改操作判断标志

	protected static final String SAVE = "save";//页面保存操作判断标志
	
	protected static final String TABNAME = "bxxx_nnzy_ylbxb";//保险信息南通职业 医疗保险
	
	protected static final String VIEWNAME = "view_bxxx_nnzy_ylbx";//页面保存操作判断标志
	
	
	/** 
	 * Method ylbxSq
	 * 医疗保险申请
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ylbxSq(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		XsxxglService xsxxglService=new XsxxglService();
		NtzyYlbxForm ylbxForm=(NtzyYlbxForm)form;
		//操作状态标识
		String doType=request.getParameter("doType");
		String xh=ylbxForm.getSave_xh();
		
		if(SAVE.equals(doType)){
			
			//医疗保险信息保存
			this.insertOperation(request, TABNAME);
		}
		
		//获取学生信息;
		HashMap<String,String>stuInfo=new HashMap<String,String>();
		HashMap<String,String>rs=(HashMap<String,String>)request.getAttribute("rs");
		if(rs!=null){
			 xh= rs.get("xh");
		}
		
		if(!"".equals(xh) && xh!=null){
			stuInfo.putAll(xsxxglService.selectStuinfo(xh));//学生基本信息
		}
		request.setAttribute("act", "save");
		request.setAttribute("rs", stuInfo);
		request.setAttribute("path", "ntzyYlbx.do?method=ylbxSq");
		FormModleCommon.commonRequestSet(request);
		request.setAttribute("nowTime", GetTime.getNowTime2());
		return mapping.findForward("ylbxSq");
	}
	
	/** 
	 * Method ylbxCx
	 * 医疗保险查询
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ylbxCx(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
       
		HttpSession session=request.getSession();
		NtzyYlbxForm ylbxForm=(NtzyYlbxForm)form;
		
		String userName=session.getAttribute("userName").toString();
		String userDep=session.getAttribute("userDep").toString();
		String userType=session.getAttribute("userType").toString();
		//操作状态标识
		String doType=request.getParameter("doType");
		
		//删除
		if(DELETE.equals(doType)){
			this.deleteOperation(request, TABNAME);
			doType=QUERY;
		}
		
		//查询
		if(QUERY.equals(doType)){
			String[] outputColumn={"tzlsh","xh","xm","xb","nj","xymc","zymc","bjmc","bxsj"};
			getQuery(request,ylbxForm);
			this.selectPageDataByPagination(request, form, TABNAME, VIEWNAME, outputColumn);
		}
		
		if("xy".equals(userType)){
			ylbxForm.setXydm(userDep);
		}
		
		if("stu".equals(userType)){
			ylbxForm.setXh(userName);
		}
		
		FormModleCommon.setNdXnXqList(request);
		FormModleCommon.setNjXyZyBjListForFdyBzr(request);
		request.setAttribute("path", "ntzyYlbx.do?method=ylbxCx");
		FormModleCommon.commonRequestSet(request);
		return mapping.findForward("ylbxCx");
	}
	
	/** 
	 * Method ylbxOne
	 * 医疗保险单条记录
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ylbxOne(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		XsxxglService xsxxglService=new XsxxglService();
		NtzyYlbxForm ylbxForm=(NtzyYlbxForm)form;
		//操作状态标识
		String doType=request.getParameter("doType");
		String act = request.getParameter("act");
		String pkValue = request.getParameter("pkValue");
		
		if(MODIFY.equals(doType)){
			this.updateOperation(request, TABNAME);
			doType=VIEW;
		}
		
		if(VIEW.equals(doType)){
			
			//医疗保险信息保存
			this.selectPageDataByOne(request, TABNAME, TABNAME, pkValue);
			HashMap<String,String>rs=(HashMap<String,String>)request.getAttribute("rs");
			rs.putAll(xsxxglService.selectStuinfo(rs.get("xh")));//学生基本信息
			request.setAttribute("rs", rs);
		}
		
		request.setAttribute("pkValue", pkValue);
		request.setAttribute("act",act );
		request.setAttribute("path", "ntzyYlbx.do?method=ylbxSq");
		FormModleCommon.commonRequestSet(request);
		request.setAttribute("nowTime", GetTime.getNowTime2());
		return mapping.findForward("ylbxSq");
	}
	
	
	
	/**
	 * 保险时间条件
	 */
	public void getQuery(HttpServletRequest request,NtzyYlbxForm ylbxForm) {
	   
	   StringBuilder sb=new StringBuilder();
	   if(!"".equals(ylbxForm.getKssj()) && ylbxForm.getKssj()!=null){
		   sb.append(" and bxsj>= ");
		   sb.append(ylbxForm.getKssj());
	   }
	   if(!"".equals(ylbxForm.getJssj()) && ylbxForm.getJssj()!=null){
		   sb.append(" and bxsj<= ");
		   sb.append(ylbxForm.getJssj());
	   }
	   request.setAttribute("annexTerm", "  "+sb.toString());
	   
	}
	
	
	/**
	 * 数据导出
	 * method expDate
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward expDate(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		try {
			this.expPageData(request, response, TABNAME, VIEWNAME, null);
		} catch (Exception e) {
			e.printStackTrace();
		}			
		
		return mapping.findForward("success");
	}
}