/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.dtjs.zjcm.kkcs;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import xgxt.action.Base;
import xgxt.action.BaseAction;
import xgxt.utils.FormModleCommon;

/** 
 * MyEclipse Struts
 * Creation date: 08-30-2010
 * 浙江传媒 旷课次数
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ZjcmKkcsAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward kkcsWh(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		HttpSession session=request.getSession();
		ZjcmKkcsForm kkcsForm=(ZjcmKkcsForm)form;
		ZjcmKkcsService service =new ZjcmKkcsService();
		
		String lx=request.getParameter("lx");
		if(Base.isNull(lx)){
			lx="wh";
		}
		String viewName="view_zjcm_dtjs_kkcs";
		String tableName="zjcm_dtjs_kkcs";
		String doType=request.getParameter("doType");
		String userType=session.getAttribute("userType").toString();
		String userDep=session.getAttribute("userDep").toString();
		
		
		if("save".equalsIgnoreCase(doType)){
			service.kkcsWh(request, kkcsForm);
			doType="qry";
		}
		if("qry".equalsIgnoreCase(doType)){
			if("wh".equalsIgnoreCase(lx)){
			String []outputColumn={"xh","xh","xm","nj","xy","zymc","bjmc","kkcs"};
			this.selectPageDataByPagination(request, form, tableName, viewName, outputColumn);
			}else if("cx".equalsIgnoreCase(lx)){
				String []outputColumn={"xh","xh","xm","xn","xqmc","nj","xy","zymc","bjmc","kkcs"};
				this.selectPageDataByPagination(request, form, tableName, "view_zjcm_pjpy_kkcscx", outputColumn);
			}
			
		}
		
		if("xy".equalsIgnoreCase(userType)){
			kkcsForm.setXydm(userDep);
		}
		
		if("wh".equalsIgnoreCase(lx)){
			kkcsForm.setXn(Base.getJxjsqxn());
			kkcsForm.setXq(Base.getJxjsqxq());
		}
		request.setAttribute("lx", lx);
		FormModleCommon.setNdXnXqList(request);
		FormModleCommon.setNjXyZyBjListForFdyBzr(request);
		request.setAttribute("path", "zjcmKkcs.do?method=kkcsWh");
		FormModleCommon.commonRequestSet(request);
		return mapping.findForward("kkcsWh");
	}
	
	/**
	 * 旷课次数信息倒出
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * */
	public ActionForward expDate(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		try {
			
			this.expPageData(request, response, "zjcm_dtjs_kkcs", "view_zjcm_dtjs_kkcs", null);
		
		} catch (Exception e) {
		
			e.printStackTrace();
		
		}			
		
		return mapping.findForward("success");
	}
}