/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.pjpy.hhgxy.pjtj;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jxl.write.WritableWorkbook;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import xgxt.action.BaseAction;
import xgxt.utils.ExcelMethods;

/** 
 * MyEclipse Struts
 * Creation date: 11-22-2010
 * 淮海工学院
 * author 裘力俊
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PjpyHhgxyPjtjAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 评奖统计
	 * Method pjtj
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward pjtj(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		PjpyHhgxyPjtjForm pjtjForm=(PjpyHhgxyPjtjForm)form;
		PjpyHhgxyPjtjService service = new PjpyHhgxyPjtjService();
		PjpyModel model=new PjpyModel();
		model.setXxlx(request.getParameter("xxlx"));
		BeanUtils.copyProperties(model,pjtjForm);
		String modelPath = servlet.getServletContext().getRealPath("")+"/print/pjpy/hhgxy_pjtj.xls";
		response.reset();
		response.setContentType("application/vnd.ms-excel");
		WritableWorkbook wwb = ExcelMethods.getWritableWorkbook(new File(
				modelPath), response.getOutputStream());
		service.pytj(wwb, model);
		return null;
	}
}