/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xszz.xcxy;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;


/** 
 * MyEclipse Struts
 * Creation date: 08-24-2009
 * 
 * XDoclet definition:
 * @struts.form name="xcxyXszzForm"
 */
public class XcxyXszzForm extends ActionForm {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5984753409271995507L;
	private String xh;
	private String xm;
	private String xn;
	private String xq;
	private String nd;
	private String nj;
	private String xy;
	private String xydm;
	private String zydm;
	private String bjdm;
	private String mz;	
	private String xb;
	private String xmdm;
	private String xmmc;
	private String xmlc;
	private String zzje;
	private String sqkssj;
	private String sqjssj;
	private String doType;
	private String act;
	private String temp;
	private String zzkssj;
	private String zzjssj;
	private String sfzh;
	private String xl;
	private String jg;
	private String lxdh;
	private String jtdz;
	private String yhkh;
	private String ykth;
	private String fkh;
	private String sqly;
	private String hkxz;
	private String jtzrs;
	private String jtysr;
	private String rjysr;
	private String yzbm;
	private String srly;
	private String chjl;
	
	private String jtcy1_xm;
	private String jtcy1_nl;
	private String jtcy1_gx;
	private String jtcy1_dw;
	private String jtcy2_xm;
	private String jtcy2_nl;
	private String jtcy2_gx;
	private String jtcy2_dw;
	private String jtcy3_xm;
	private String jtcy3_nl;
	private String jtcy3_gx;
	private String jtcy3_dw;
	private String jtcy4_xm;
	private String jtcy4_nl;
	private String jtcy4_gx;
	private String jtcy4_dw;
	
	private String xysh;
	private String xyshyj;
	private String xxsh;
	private String xxshyj;
	private String xysx;
	private String bbys;
	private String xymc;
	private String tableName;
	FormFile uploadFile;
	
	
	public String getXysx() {
		return xysx;
	}
	public void setXysx(String xysx) {
		this.xysx = xysx;
	}
	public String getBjdm() {
		return bjdm;
	}
	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}
	public String getMz() {
		return mz;
	}
	public void setMz(String mz) {
		this.mz = mz;
	}
	public String getNd() {
		return nd;
	}
	public void setNd(String nd) {
		this.nd = nd;
	}
	public String getNj() {
		return nj;
	}
	public void setNj(String nj) {
		this.nj = nj;
	}
	public String getSqjssj() {
		return sqjssj;
	}
	public void setSqjssj(String sqjssj) {
		this.sqjssj = sqjssj;
	}
	public String getSqkssj() {
		return sqkssj;
	}
	public void setSqkssj(String sqkssj) {
		this.sqkssj = sqkssj;
	}
	public String getXb() {
		return xb;
	}
	public void setXb(String xb) {
		this.xb = xb;
	}
	public String getXh() {
		return xh;
	}
	public void setXh(String xh) {
		this.xh = xh;
	}
	public String getXm() {
		return xm;
	}
	public void setXm(String xm) {
		this.xm = xm;
	}
	public String getZzje() {
		return zzje;
	}
	public void setZzje(String zzje) {
		this.zzje = zzje;
	}
	public String getXmlc() {
		return xmlc;
	}
	public void setXmlc(String xmlc) {
		this.xmlc = xmlc;
	}
	public String getXmmc() {
		return xmmc;
	}
	public void setXmmc(String xmmc) {
		this.xmmc = xmmc;
	}
	public String getXn() {
		return xn;
	}
	public void setXn(String xn) {
		this.xn = xn;
	}
	public String getXq() {
		return xq;
	}
	public void setXq(String xq) {
		this.xq = xq;
	}
	public String getXydm() {
		return xydm;
	}
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
	public String getZydm() {
		return zydm;
	}
	public void setZydm(String zydm) {
		this.zydm = zydm;
	}
	public String getDoType() {
		return doType;
	}
	public void setDoType(String doType) {
		this.doType = doType;
	}
	public String getXmdm() {
		return xmdm;
	}
	public void setXmdm(String xmdm) {
		this.xmdm = xmdm;
	}
	public String getAct() {
		return act;
	}
	public void setAct(String act) {
		this.act = act;
	}
	public String getTemp() {
		return temp;
	}
	public void setTemp(String temp) {
		this.temp = temp;
	}
	public String getZzjssj() {
		return zzjssj;
	}
	public void setZzjssj(String zzjssj) {
		this.zzjssj = zzjssj;
	}
	public String getZzkssj() {
		return zzkssj;
	}
	public void setZzkssj(String zzkssj) {
		this.zzkssj = zzkssj;
	}
	public String getFkh() {
		return fkh;
	}
	public void setFkh(String fkh) {
		this.fkh = fkh;
	}
	public String getHkxz() {
		return hkxz;
	}
	public void setHkxz(String hkxz) {
		this.hkxz = hkxz;
	}
	public String getJg() {
		return jg;
	}
	public void setJg(String jg) {
		this.jg = jg;
	}
	public String getJtcy1_dw() {
		return jtcy1_dw;
	}
	public void setJtcy1_dw(String jtcy1_dw) {
		this.jtcy1_dw = jtcy1_dw;
	}
	public String getJtcy1_gx() {
		return jtcy1_gx;
	}
	public void setJtcy1_gx(String jtcy1_gx) {
		this.jtcy1_gx = jtcy1_gx;
	}
	public String getJtcy1_nl() {
		return jtcy1_nl;
	}
	public void setJtcy1_nl(String jtcy1_nl) {
		this.jtcy1_nl = jtcy1_nl;
	}
	public String getJtcy1_xm() {
		return jtcy1_xm;
	}
	public void setJtcy1_xm(String jtcy1_xm) {
		this.jtcy1_xm = jtcy1_xm;
	}
	public String getJtcy2_dw() {
		return jtcy2_dw;
	}
	public void setJtcy2_dw(String jtcy2_dw) {
		this.jtcy2_dw = jtcy2_dw;
	}
	public String getJtcy2_gx() {
		return jtcy2_gx;
	}
	public void setJtcy2_gx(String jtcy2_gx) {
		this.jtcy2_gx = jtcy2_gx;
	}
	public String getJtcy2_nl() {
		return jtcy2_nl;
	}
	public void setJtcy2_nl(String jtcy2_nl) {
		this.jtcy2_nl = jtcy2_nl;
	}
	public String getJtcy2_xm() {
		return jtcy2_xm;
	}
	public void setJtcy2_xm(String jtcy2_xm) {
		this.jtcy2_xm = jtcy2_xm;
	}
	public String getJtcy3_dw() {
		return jtcy3_dw;
	}
	public void setJtcy3_dw(String jtcy3_dw) {
		this.jtcy3_dw = jtcy3_dw;
	}
	public String getJtcy3_gx() {
		return jtcy3_gx;
	}
	public void setJtcy3_gx(String jtcy3_gx) {
		this.jtcy3_gx = jtcy3_gx;
	}
	public String getJtcy3_nl() {
		return jtcy3_nl;
	}
	public void setJtcy3_nl(String jtcy3_nl) {
		this.jtcy3_nl = jtcy3_nl;
	}
	public String getJtcy3_xm() {
		return jtcy3_xm;
	}
	public void setJtcy3_xm(String jtcy3_xm) {
		this.jtcy3_xm = jtcy3_xm;
	}
	public String getJtcy4_dw() {
		return jtcy4_dw;
	}
	public void setJtcy4_dw(String jtcy4_dw) {
		this.jtcy4_dw = jtcy4_dw;
	}
	public String getJtcy4_gx() {
		return jtcy4_gx;
	}
	public void setJtcy4_gx(String jtcy4_gx) {
		this.jtcy4_gx = jtcy4_gx;
	}
	public String getJtcy4_nl() {
		return jtcy4_nl;
	}
	public void setJtcy4_nl(String jtcy4_nl) {
		this.jtcy4_nl = jtcy4_nl;
	}
	public String getJtcy4_xm() {
		return jtcy4_xm;
	}
	public void setJtcy4_xm(String jtcy4_xm) {
		this.jtcy4_xm = jtcy4_xm;
	}
	public String getJtdz() {
		return jtdz;
	}
	public void setJtdz(String jtdz) {
		this.jtdz = jtdz;
	}
	public String getJtysr() {
		return jtysr;
	}
	public void setJtysr(String jtysr) {
		this.jtysr = jtysr;
	}
	public String getJtzrs() {
		return jtzrs;
	}
	public void setJtzrs(String jtzrs) {
		this.jtzrs = jtzrs;
	}
	public String getLxdh() {
		return lxdh;
	}
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}
	public String getRjysr() {
		return rjysr;
	}
	public void setRjysr(String rjysr) {
		this.rjysr = rjysr;
	}
	public String getSfzh() {
		return sfzh;
	}
	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}
	public String getSqly() {
		return sqly;
	}
	public void setSqly(String sqly) {
		this.sqly = sqly;
	}
	public String getSrly() {
		return srly;
	}
	public void setSrly(String srly) {
		this.srly = srly;
	}
	public String getXl() {
		return xl;
	}
	public void setXl(String xl) {
		this.xl = xl;
	}
	public String getYhkh() {
		return yhkh;
	}
	public void setYhkh(String yhkh) {
		this.yhkh = yhkh;
	}
	public String getYkth() {
		return ykth;
	}
	public void setYkth(String ykth) {
		this.ykth = ykth;
	}
	public String getYzbm() {
		return yzbm;
	}
	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}
	public String getChjl() {
		return chjl;
	}
	public void setChjl(String chjl) {
		this.chjl = chjl;
	}
	public String getXy() {
		return xy;
	}
	public void setXy(String xy) {
		this.xy = xy;
	}
	public String getXxsh() {
		return xxsh;
	}
	public void setXxsh(String xxsh) {
		this.xxsh = xxsh;
	}
	public String getXxshyj() {
		return xxshyj;
	}
	public void setXxshyj(String xxshyj) {
		this.xxshyj = xxshyj;
	}
	public String getXysh() {
		return xysh;
	}
	public void setXysh(String xysh) {
		this.xysh = xysh;
	}
	public String getXyshyj() {
		return xyshyj;
	}
	public void setXyshyj(String xyshyj) {
		this.xyshyj = xyshyj;
	}
	public String getBbys() {
		return bbys;
	}
	public void setBbys(String bbys) {
		this.bbys = bbys;
	}
	public String getXymc() {
		return xymc;
	}
	public void setXymc(String xymc) {
		this.xymc = xymc;
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public FormFile getUploadFile() {
		return uploadFile;
	}
	public void setUploadFile(FormFile uploadFile) {
		this.uploadFile = uploadFile;
	}
}
	
	