/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xsh.stgl.dekthdqh;
import org.apache.struts.action.ActionForm;

import xgxt.utils.Pages;


/** 
 * MyEclipse Struts
 * Creation date: 07-24-2010
 * 
 * XDoclet definition:
 * @struts.form name="sjxyDektqhForm"
 */
public class SjxyDektqhForm extends ActionForm {
	 private String xxsh;     //学校审核
	 private String jbsj;     //举办时间
	 private String hdfzr;     //活动负责人
	 private String ssh;     //宿舍号
	 private String sfbx;     //是否报销
	 private String hddd;     //活动地点
	 private String cjdxrs;     //参加对象及人数
	 private String yqjb;     //邀请嘉宾
	 private String hdkxfx;     //活动可行性分析
	 private String sjcxrs;     //实际出席人数
	 private String hdmdyy;     //活动目的和意义
	 private String hdxyjf;     //活动需要经费
	 private String hdjfys;     //活动经费预算清单
	 private String hdxg;     //活动效果
	 private String sfytp;     //是否有图片
	 private String hdmc;     //活动名称
	 private String lxfs;     //联系方式
	 private String jbbm;     //举办部门
	 private String sqsj;     //活动申请时间
	 private String shpjyj;     //团委宣传部时候评价、意见
	 private String hdsssjb;     //活动实施时间表
	 private String sfytxg;     //是否有通讯稿
	 private String xxshsj;     //学校审核时间
	 private String zdls;     //指导老师
	 private String stlhhzxyj;			//社团联合会主席意见
	 private String xshzxyj;
	 private String twsjyj;	//团委书记意见
	 
	 private String save_hdkxfx;     //活动可行性分析
	 private String save_sjcxrs;     //实际出席人数
	 private String save_sfbx;     //是否报销
	 private String save_xxsh;     //学校审核
	 private String save_jbsj;     //举办时间
	 private String save_lxfs;     //联系方式
	 private String save_cjdxrs;     //参加对象及人数
	 private String save_hdsssjb;     //活动实施时间表
	 private String save_sfytxg;     //是否有通讯稿
	 private String save_xxshsj;     //学校审核时间
	 private String save_jbbm;     //举办部门
	 private String save_hdfzr;     //活动负责人
	 private String save_hdxyjf;     //活动需要经费
	 private String save_sqsj;     //活动申请时间
	 private String save_sfytp;     //是否有图片
	 private String save_hdmdyy;     //活动目的和意义
	 private String save_hdjfys;     //活动经费预算清单
	 private String save_shpjyj;     //团委宣传部时候评价、意见
	 private String save_hdmc;     //活动名称
	 private String save_hddd;     //活动地点
	 private String save_zdls;     //指导老师
	 private String save_ssh;     //宿舍号
	 private String save_yqjb;     //邀请嘉宾
	 private String save_hdxg;     //活动效果
	 private String save_stlhhzxyj;			//社团联合会主席意见
	 private String save_xshzxyj;
	 private String save_twsjyj;	//团委书记意见
	 
	 private String queryequals_xxsh;
	 private String querylike_hdmc;
	 private String querylike_jbbm;
	 private String querylike_jbsj;
	 private String querylike_hddd;
	 private String querylike_hdfzr;
	 private String querylike_zdls;
	private Pages pages=new Pages();
	public Pages getPages() {
		return pages;
	}
	public void setPages(Pages pages) {
		this.pages = pages;
	}
	public String getCjdxrs() {
		return cjdxrs;
	}
	public void setCjdxrs(String cjdxrs) {
		this.cjdxrs = cjdxrs;
	}
	public String getHddd() {
		return hddd;
	}
	public void setHddd(String hddd) {
		this.hddd = hddd;
	}
	public String getHdfzr() {
		return hdfzr;
	}
	public void setHdfzr(String hdfzr) {
		this.hdfzr = hdfzr;
	}
	public String getHdjfys() {
		return hdjfys;
	}
	public void setHdjfys(String hdjfys) {
		this.hdjfys = hdjfys;
	}
	public String getHdkxfx() {
		return hdkxfx;
	}
	public void setHdkxfx(String hdkxfx) {
		this.hdkxfx = hdkxfx;
	}
	public String getHdmc() {
		return hdmc;
	}
	public void setHdmc(String hdmc) {
		this.hdmc = hdmc;
	}
	public String getHdmdyy() {
		return hdmdyy;
	}
	public void setHdmdyy(String hdmdyy) {
		this.hdmdyy = hdmdyy;
	}
	public String getHdsssjb() {
		return hdsssjb;
	}
	public void setHdsssjb(String hdsssjb) {
		this.hdsssjb = hdsssjb;
	}
	public String getHdxyjf() {
		return hdxyjf;
	}
	public void setHdxyjf(String hdxyjf) {
		this.hdxyjf = hdxyjf;
	}
	public String getJbbm() {
		return jbbm;
	}
	public void setJbbm(String jbbm) {
		this.jbbm = jbbm;
	}
	public String getJbsj() {
		return jbsj;
	}
	public void setJbsj(String jbsj) {
		this.jbsj = jbsj;
	}
	public String getLxfs() {
		return lxfs;
	}
	public void setLxfs(String lxfs) {
		this.lxfs = lxfs;
	}
	public String getSave_cjdxrs() {
		return save_cjdxrs;
	}
	public void setSave_cjdxrs(String save_cjdxrs) {
		this.save_cjdxrs = save_cjdxrs;
	}
	public String getSave_hddd() {
		return save_hddd;
	}
	public void setSave_hddd(String save_hddd) {
		this.save_hddd = save_hddd;
	}
	public String getSave_hdfzr() {
		return save_hdfzr;
	}
	public void setSave_hdfzr(String save_hdfzr) {
		this.save_hdfzr = save_hdfzr;
	}
	public String getSave_hdjfys() {
		return save_hdjfys;
	}
	public void setSave_hdjfys(String save_hdjfys) {
		this.save_hdjfys = save_hdjfys;
	}
	public String getSave_hdkxfx() {
		return save_hdkxfx;
	}
	public void setSave_hdkxfx(String save_hdkxfx) {
		this.save_hdkxfx = save_hdkxfx;
	}
	public String getSave_hdmc() {
		return save_hdmc;
	}
	public void setSave_hdmc(String save_hdmc) {
		this.save_hdmc = save_hdmc;
	}
	public String getSave_hdmdyy() {
		return save_hdmdyy;
	}
	public void setSave_hdmdyy(String save_hdmdyy) {
		this.save_hdmdyy = save_hdmdyy;
	}
	public String getSave_hdsssjb() {
		return save_hdsssjb;
	}
	public void setSave_hdsssjb(String save_hdsssjb) {
		this.save_hdsssjb = save_hdsssjb;
	}
	public String getSave_hdxyjf() {
		return save_hdxyjf;
	}
	public void setSave_hdxyjf(String save_hdxyjf) {
		this.save_hdxyjf = save_hdxyjf;
	}
	public String getSave_jbbm() {
		return save_jbbm;
	}
	public void setSave_jbbm(String save_jbbm) {
		this.save_jbbm = save_jbbm;
	}
	public String getSave_jbsj() {
		return save_jbsj;
	}
	public void setSave_jbsj(String save_jbsj) {
		this.save_jbsj = save_jbsj;
	}
	public String getSave_lxfs() {
		return save_lxfs;
	}
	public void setSave_lxfs(String save_lxfs) {
		this.save_lxfs = save_lxfs;
	}
	public String getSave_ssh() {
		return save_ssh;
	}
	public void setSave_ssh(String save_ssh) {
		this.save_ssh = save_ssh;
	}
	public String getSave_yqjb() {
		return save_yqjb;
	}
	public void setSave_yqjb(String save_yqjb) {
		this.save_yqjb = save_yqjb;
	}
	public String getSave_zdls() {
		return save_zdls;
	}
	public void setSave_zdls(String save_zdls) {
		this.save_zdls = save_zdls;
	}
	public String getSsh() {
		return ssh;
	}
	public void setSsh(String ssh) {
		this.ssh = ssh;
	}
	public String getYqjb() {
		return yqjb;
	}
	public void setYqjb(String yqjb) {
		this.yqjb = yqjb;
	}
	public String getZdls() {
		return zdls;
	}
	public void setZdls(String zdls) {
		this.zdls = zdls;
	}
	public String getSave_xxsh() {
		return save_xxsh;
	}
	public void setSave_xxsh(String save_xxsh) {
		this.save_xxsh = save_xxsh;
	}
	public String getSave_xxshsj() {
		return save_xxshsj;
	}
	public void setSave_xxshsj(String save_xxshsj) {
		this.save_xxshsj = save_xxshsj;
	}
	public String getXxsh() {
		return xxsh;
	}
	public void setXxsh(String xxsh) {
		this.xxsh = xxsh;
	}
	public String getXxshsj() {
		return xxshsj;
	}
	public void setXxshsj(String xxshsj) {
		this.xxshsj = xxshsj;
	}
	public String getHdxg() {
		return hdxg;
	}
	public void setHdxg(String hdxg) {
		this.hdxg = hdxg;
	}
	public String getSave_hdxg() {
		return save_hdxg;
	}
	public void setSave_hdxg(String save_hdxg) {
		this.save_hdxg = save_hdxg;
	}
	public String getSave_sfbx() {
		return save_sfbx;
	}
	public void setSave_sfbx(String save_sfbx) {
		this.save_sfbx = save_sfbx;
	}
	public String getSave_sfytp() {
		return save_sfytp;
	}
	public void setSave_sfytp(String save_sfytp) {
		this.save_sfytp = save_sfytp;
	}
	public String getSave_sfytxg() {
		return save_sfytxg;
	}
	public void setSave_sfytxg(String save_sfytxg) {
		this.save_sfytxg = save_sfytxg;
	}
	public String getSave_shpjyj() {
		return save_shpjyj;
	}
	public void setSave_shpjyj(String save_shpjyj) {
		this.save_shpjyj = save_shpjyj;
	}
	public String getSave_sjcxrs() {
		return save_sjcxrs;
	}
	public void setSave_sjcxrs(String save_sjcxrs) {
		this.save_sjcxrs = save_sjcxrs;
	}
	public String getSave_sqsj() {
		return save_sqsj;
	}
	public void setSave_sqsj(String save_sqsj) {
		this.save_sqsj = save_sqsj;
	}
	public String getSfbx() {
		return sfbx;
	}
	public void setSfbx(String sfbx) {
		this.sfbx = sfbx;
	}
	public String getSfytp() {
		return sfytp;
	}
	public void setSfytp(String sfytp) {
		this.sfytp = sfytp;
	}
	public String getSfytxg() {
		return sfytxg;
	}
	public void setSfytxg(String sfytxg) {
		this.sfytxg = sfytxg;
	}
	public String getShpjyj() {
		return shpjyj;
	}
	public void setShpjyj(String shpjyj) {
		this.shpjyj = shpjyj;
	}
	public String getSjcxrs() {
		return sjcxrs;
	}
	public void setSjcxrs(String sjcxrs) {
		this.sjcxrs = sjcxrs;
	}
	public String getSqsj() {
		return sqsj;
	}
	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}
	public String getSave_stlhhzxyj() {
		return save_stlhhzxyj;
	}
	public void setSave_stlhhzxyj(String save_stlhhzxyj) {
		this.save_stlhhzxyj = save_stlhhzxyj;
	}
	public String getSave_twsjyj() {
		return save_twsjyj;
	}
	public void setSave_twsjyj(String save_twsjyj) {
		this.save_twsjyj = save_twsjyj;
	}
	public String getSave_xshzxyj() {
		return save_xshzxyj;
	}
	public void setSave_xshzxyj(String save_xshzxyj) {
		this.save_xshzxyj = save_xshzxyj;
	}
	public String getStlhhzxyj() {
		return stlhhzxyj;
	}
	public void setStlhhzxyj(String stlhhzxyj) {
		this.stlhhzxyj = stlhhzxyj;
	}
	public String getTwsjyj() {
		return twsjyj;
	}
	public void setTwsjyj(String twsjyj) {
		this.twsjyj = twsjyj;
	}
	public String getXshzxyj() {
		return xshzxyj;
	}
	public void setXshzxyj(String xshzxyj) {
		this.xshzxyj = xshzxyj;
	}
	public String getQueryequals_xxsh() {
		return queryequals_xxsh;
	}
	public void setQueryequals_xxsh(String queryequals_xxsh) {
		this.queryequals_xxsh = queryequals_xxsh;
	}
	public String getQuerylike_hddd() {
		return querylike_hddd;
	}
	public void setQuerylike_hddd(String querylike_hddd) {
		this.querylike_hddd = querylike_hddd;
	}
	public String getQuerylike_hdfzr() {
		return querylike_hdfzr;
	}
	public void setQuerylike_hdfzr(String querylike_hdfzr) {
		this.querylike_hdfzr = querylike_hdfzr;
	}
	public String getQuerylike_hdmc() {
		return querylike_hdmc;
	}
	public void setQuerylike_hdmc(String querylike_hdmc) {
		this.querylike_hdmc = querylike_hdmc;
	}
	public String getQuerylike_jbbm() {
		return querylike_jbbm;
	}
	public void setQuerylike_jbbm(String querylike_jbbm) {
		this.querylike_jbbm = querylike_jbbm;
	}
	public String getQuerylike_jbsj() {
		return querylike_jbsj;
	}
	public void setQuerylike_jbsj(String querylike_jbsj) {
		this.querylike_jbsj = querylike_jbsj;
	}
	public String getQuerylike_zdls() {
		return querylike_zdls;
	}
	public void setQuerylike_zdls(String querylike_zdls) {
		this.querylike_zdls = querylike_zdls;
	}
}