/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xsxx.comm.jbxx;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import xgxt.form.CommanForm;
import xgxt.studentInfo.ynys.XsxxYnysService;
import xgxt.utils.FormModleCommon;
import xgxt.xsxx.comm.jbsz.XsxxJbszForm;

import com.zfsoft.basic.BasicAction;

/**
 * <p>
 * Title: 学工管理系统
 * </p>
 * <p>
 * Description: 学生信息_学生基本信息-action类
 * </p>
 * <p>
 * Copyright: Copyright (c) 2011
 * </p>
 * <p>
 * Company: zfsoft
 * </p>
 * 
 * @author qlj
 * @version 1.0
 */

public class XsxxJbxxAction extends BasicAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 学生基本信息维护
	 * Method xsxxwh
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward xsxxwh(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		XsxxJbxxForm myForm=new XsxxJbxxForm();
		XsxxJbszForm model=new XsxxJbszForm();
		XsxxJbxxService service =new XsxxJbxxService();
		XsxxYnysService ynysService = new XsxxYnysService();
		
		model.setSearch_sfqy("是");
		myForm.setSearch_sfqy("是");
		
		CommanForm dataSearchForm =new CommanForm();
		//显示区域
		request.setAttribute("xsqList",service.getXsqnrList(myForm));
		//字段位置
		request.setAttribute("zdwzList", service.getZdwzList(myForm));
		//启用字段
		request.setAttribute("qyzdList", service.getQyzdList(myForm));
		//显示区显示字段
		request.setAttribute("xsqzdList", service.getXsqZdwzList(myForm));
		
		//加载下拉列表
		service.setXlkList(myForm, request);
		
		service.checkZdSize(request,model);
		
		HashMap<String,Object>rs=new HashMap<String,Object>();
		
		rs.put("ssList", ynysService.getSsList());
		rs.put("shiList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("shiList"));
		rs.put("xianList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("xianList"));
		
		request.setAttribute("rs", rs);
		request.setAttribute("pk", myForm.getPk());
		request.setAttribute("ssList", ynysService.getSsList());
        request.setAttribute("shiList", ynysService.getShiList(dataSearchForm.getJgshen()).get("shiList"));
		request.setAttribute("xianList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("xianList"));
		FormModleCommon.setNjXyZyBjListForFdyBzr(request);
		return mapping.findForward("xsxxwh");
	}
	
	/** 
	 * 学生信息基本信息(显示结构)构建
	 * Method xsxxwh
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward xsjggj(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		XsxxJbxxForm myForm=new XsxxJbxxForm();
		XsxxJbszForm model=new XsxxJbszForm();
		XsxxJbxxService service =new XsxxJbxxService();
		XsxxYnysService ynysService = new XsxxYnysService();
		
		model.setSearch_sfqy("是");
		myForm.setSearch_sfqy("是");
		
		CommanForm dataSearchForm =new CommanForm();
		//显示区域
		request.setAttribute("xsqList",service.getXsqnrList(myForm));
		//字段位置
		request.setAttribute("zdwzList", service.getZdwzList(myForm));
		//启用字段
		request.setAttribute("qyzdList", service.getQyzdList(myForm));
		//显示区显示字段
		request.setAttribute("xsqzdList", service.getXsqZdwzList(myForm));
		//加载下拉列表
		service.setXlkList(myForm, request);
		
		service.checkZdSize(request,model);
		
		HashMap<String,Object>rs=new HashMap<String,Object>();
		rs.put("ssList", ynysService.getSsList());
		rs.put("shiList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("shiList"));
		rs.put("xianList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("xianList"));
		request.setAttribute("rs", rs);
		request.setAttribute("ssList", ynysService.getSsList());
        request.setAttribute("shiList", ynysService.getShiList(dataSearchForm.getJgshen()).get("shiList"));
		request.setAttribute("xianList",  ynysService.getShiList(dataSearchForm.getJgshen()).get("xianList"));
		FormModleCommon.setNjXyZyBjListForFdyBzr(request);
		return mapping.findForward("xsxxwh");
	}
}