/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xslx.action;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-06-2007
 * 
 * XDoclet definition:
 * @struts.form name="xslxForm"
 */
public class XslxForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */

	private String xh;//学号
	private String xm;//姓名
	private String xb;//性别
	private String nj;//年级
	private String xydm;//学院代码
	private String xymc;//学院名称
	private String zydm;//专业代码
	private String zymc;//专业名称
	private String bjdm;//班级代码
	private String bjmc;//班级名称
	private String bzryj;//班主任意见
	private String xdzsyj;//系党支书意见
	private String ywsyj;//医务室意见
	private String tsgyj;//图书馆意见
	private String cwcyj;//财务处意见
	private String sqglbyj;//社区管理部意见
	private String xscyj;//学生处意见
	private String oracleItem;
	private String sql;
	private String jbxx;
	private String shdw;//审核单位
	private String shjg;//审核结果
	private String dzsxm;//党支书姓名
	
	
	public String getShdw() {
		return shdw;
	}
	public void setShdw(String shdw) {
		this.shdw = shdw;
	}
	public String getShjg() {
		return shjg;
	}
	public void setShjg(String shjg) {
		this.shjg = shjg;
	}
	public String getJbxx() {
		return jbxx;
	}
	public void setJbxx(String jbxx) {
		this.jbxx = jbxx;
	}
	public String getOracleItem() {
		return oracleItem;
	}
	public void setOracleItem(String oracleItem) {
		this.oracleItem = oracleItem;
	}
	public String getSql() {
		return sql;
	}
	public void setSql(String sql) {
		this.sql = sql;
	}
	public String getBjdm() {
		return bjdm;
	}
	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}
	public String getBjmc() {
		return bjmc;
	}
	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}
	public String getBzryj() {
		return bzryj;
	}
	public void setBzryj(String bzryj) {
		this.bzryj = bzryj;
	}
	public String getCwcyj() {
		return cwcyj;
	}
	public void setCwcyj(String cwcyj) {
		this.cwcyj = cwcyj;
	}
	public String getSqglbyj() {
		return sqglbyj;
	}
	public void setSqglbyj(String sqglbyj) {
		this.sqglbyj = sqglbyj;
	}
	public String getTsgyj() {
		return tsgyj;
	}
	public void setTsgyj(String tsgyj) {
		this.tsgyj = tsgyj;
	}
	public String getXb() {
		return xb;
	}
	public void setXb(String xb) {
		this.xb = xb;
	}
	public String getXdzsyj() {
		return xdzsyj;
	}
	public void setXdzsyj(String xdzsyj) {
		this.xdzsyj = xdzsyj;
	}
	public String getXh() {
		return xh;
	}
	public void setXh(String xh) {
		this.xh = xh;
	}
	public String getXm() {
		return xm;
	}
	public void setXm(String xm) {
		this.xm = xm;
	}
	public String getXscyj() {
		return xscyj;
	}
	public void setXscyj(String xscyj) {
		this.xscyj = xscyj;
	}
	public String getXydm() {
		return xydm;
	}
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
	public String getXymc() {
		return xymc;
	}
	public void setXymc(String xymc) {
		this.xymc = xymc;
	}
	public String getYwsyj() {
		return ywsyj;
	}
	public void setYwsyj(String ywsyj) {
		this.ywsyj = ywsyj;
	}
	public String getZydm() {
		return zydm;
	}
	public void setZydm(String zydm) {
		this.zydm = zydm;
	}
	public String getZymc() {
		return zymc;
	}
	public void setZymc(String zymc) {
		this.zymc = zymc;
	}
	public String getNj() {
		return nj;
	}
	public void setNj(String nj) {
		this.nj = nj;
	}
	public String getDzsxm() {
		return dzsxm;
	}
	public void setDzsxm(String dzsxm) {
		this.dzsxm = dzsxm;
	}
	
}