/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.studentInfo.ahjzgyxy;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import xgxt.action.Base;
import xgxt.base.DealString;
import xgxt.utils.Fdypd;
/**
 * <p>Title: 学生工作管理系统</p>
 * <p>Description: 安徽建筑职业技术学院学生信息Action
 * <p>Copyright: Copyright (c) 2008</p>
 * <p>Company: zfsoft</p>
 * <p>Author: LP</p>
 * <p>Version: 1.0</p>
 * <p>Time: 2009-09-08</p>
 */
public class XsxxAhjzgyxyAction extends DispatchAction {
	/**
	 * 学生分类管理查询
	 * @throws Exception 
	 */
	public ActionForward stuTypeManage (ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		XsxxAhjzgyxyForm myForm = (XsxxAhjzgyxyForm)form;
		HttpSession session = request.getSession();
		String userType = (String)session.getAttribute("userType");
		String userDep = (String)session.getAttribute("userDep");
		String userName = (String)session.getAttribute("userName");
		XsxxAhjzgyxyService service = new XsxxAhjzgyxyService();
		String checkedValue = "";
		boolean doQx = false;
		if("stu".equalsIgnoreCase(userType)){//学生无操作权限
			request.setAttribute("errMsg", "学生无权访问该页面！");
			return new ActionForward("/errMsg.do", false);
		}
		if(Fdypd.isFdy(userName)){
			userType = "isFdy";
	    }else if("xy".equalsIgnoreCase(userType)){
			myForm.setXydm(userDep);
		}		
        if(session.getAttribute("fdyQx").toString().equalsIgnoreCase("true")){
        	doQx = true;
        }
        request.setAttribute("doQx",doQx);
        if("go".equalsIgnoreCase(request.getParameter("go"))){
        	StuTypeModel model = new StuTypeModel();       	
        	myForm.setXh(DealString.toGBK(myForm.getXh()).trim());
        	myForm.setXm(DealString.toGBK(myForm.getXm()).trim());
    		BeanUtils.copyProperties(model,myForm);
        	ArrayList<List> rs = service.serv_getStuTypeManage(model,userType);
        	List<HashMap<String, String>> topTr = service.serv_getStuTypeManageTitle();;
    	    request.setAttribute("rsNum", (rs != null && !"".equals(rs))?rs.size():"0");   		 
    		request.setAttribute("rs", rs);
    		request.setAttribute("topTr", topTr);
    		checkedValue = service.getLxChecked(model);
        }
		setNjXyZyBjList(request,myForm);		
		request.setAttribute("checkedValue",checkedValue);
		request.setAttribute("userType",userType);
		return mapping.findForward("stuTypeManage");
	}
	/**
	 * 学生分类信息保存
	 * @throws Exception 
	 */
	public ActionForward stuTypeSave(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		StuTypeModel model = new StuTypeModel();
		XsxxAhjzgyxyForm myForm = (XsxxAhjzgyxyForm)form;
		BeanUtils.copyProperties(model,myForm);
		XsxxAhjzgyxyService service = new XsxxAhjzgyxyService();
		service.serv_stuTypeSave(model);
		return stuTypeManage(mapping, form, request, response);
	}
	public void setNjXyZyBjList(HttpServletRequest request,XsxxAhjzgyxyForm myForm) {
		//	    在request保存年级学院专业班级List的方法
		HttpSession session =request.getSession();		
		String userName = session.getAttribute("userName").toString();
		String xy = myForm.getXydm();
		String zy =  myForm.getZydm();
		String bj =  myForm.getBjdm();
		String nj =  myForm.getNj();
		//
		xy = (xy == null) ? "" : xy;
		zy = (zy == null) ? "" : zy;
		bj = (bj == null) ? "" : bj;
		nj = (nj == null) ? "" : nj;


		String bjKey = xy + "!!" + zy + "!!" + nj;
		request.setAttribute("njList", Base.getNjList());
		request.setAttribute("ndList", Base.getXnndList());
		request.setAttribute("xnList", Base.getXnndList());
		request.setAttribute("xyList", Base.getXyList());
		request.setAttribute("zyList", (Base.getZyMap()).get(xy));
		request.setAttribute("bjList", (Base.getBjMap()).get(bjKey));
		if(Fdypd.isFdy(userName)){
			//辅导员登录
			request.setAttribute("bjList", Fdypd.getFdybjList (userName));// 发送班级列表
			request.setAttribute("zyList", Fdypd.getFdyZyList (userName));// 发送班级列表					
		}
	}

}