/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xljk.zxzx.form;

import java.util.Collection;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import xgxt.base.DealString;
import xgxt.utils.Pages;
/** 
 * MyEclipse Struts
 * Creation date: 06-14-2007
 * 
 * XDoclet definition:
 * @struts.form name="xljk_zxsxx_Form"
 */
public class xljk_zxsxx_Form extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */
	
	private String errMsg;
	private String[] errMsgs;
	
	DealString deal = new DealString();
	private String userType="";
	private String tableName="";
	private String realTable="";
	private String pk="";
	private String zxxbh="";//咨询师编号
	private String zxxxm="";//咨询师姓名
	private String sex="";//咨询师性别
	private String zxxmm="";
	private String zxxzg="";
	private String jj="";
	private Collection rs=null;
	private String act="";
	private String doType="";
	private List list=null;
	private String message="";
	private String xn_id="";
	private String sex_dm="";
	private String zgh;//职工号
	private String xm;//姓名
	private String querylike_zgh;//职工号
	private String querylike_xm;//姓名
	private String queryequals_bmdm;//部门代码
	private String bmdm;//部门代码
	private String fdyxx;
	private String zxsxx;
	private String ppzxs;
	private String ppzxsxx;
	private String zxszc;
	
	private String[] checkVal;// 批处理
	
	private HttpServletRequest request;
	private Pages pages=new Pages();
	
	public HttpServletRequest getRequest() {
		return request;
	}

	public void setRequest(HttpServletRequest request) {
		this.request = request;
	}

	public String getSex_dm() {
		return sex_dm;
	}

	public void setSex_dm(String sex_dm) {
		this.sex_dm = sex_dm;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public List getList() {
		return list;
	}

	public void setList(List list) {
		this.list = list;
	}

	public String getAct() {
		return act;
	}

	public void setAct(String act) {
		this.act = act;
	}

	public String getDoType() {
		return doType;
	}

	public void setDoType(String doType) {
		this.doType = doType;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.zxxbh=DealString.toGBK(request.getParameter("zxxbh"));
		this.act= request.getParameter("act");
		this.doType=request.getParameter("doType");
		this.zxxxm=DealString.toGBK(request.getParameter("zxxxm"));
		this.zxxzg=DealString.toGBK(request.getParameter("zxxzg"));
		this.zxxmm=DealString.toGBK(request.getParameter("zxxmm"));
		this.jj=DealString.toGBK(request.getParameter("jj"));
		this.tableName=request.getParameter("tableName");
		this.realTable=request.getParameter("realTable");
		this.pk=request.getParameter("pk");
		this.xn_id=request.getParameter("xn_id");
		this.zxszc=request.getParameter("zxszc");
		String sex=request.getParameter("sex");
		String sex_dm=request.getParameter("sex_dm");
		if(sex!=null&&!sex.equalsIgnoreCase(""))
		{
			if(sex.equals("1"))
			{
				this.sex_dm=sex;
				this.sex="男";
			}
			if(sex.equals("2"))
			{
				this.sex_dm=sex;
				this.sex="女";
			}
		}
		if(sex_dm!=null&&!sex_dm.equalsIgnoreCase(""))
		{
			if(sex_dm.equals("1"))
			{
				this.sex_dm=sex_dm;
				this.sex="男";
			}
			if(sex_dm.equals("2"))
			{
				this.sex_dm=sex_dm;
				this.sex="女";
			}
		}
		return null;
	}
	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.act="";
		this.doType="";
		this.jj="";
		this.list=null;
		this.pk="";
		this.realTable="";
		this.rs=null;
		this.sex="";
		this.tableName="";
		this.userType="";
		this.zxxbh="";
		this.zxxmm="";
		this.zxxxm="";
		this.zxxzg="";
		this.message="";
		this.sex_dm="";
	}

	public String getPk() {
		return pk;
	}

	public void setPk(String pk) {
		this.pk = pk;
	}

	public String getRealTable() {
		return realTable;
	}

	public void setRealTable(String realTable) {
		this.realTable = realTable;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Collection getRs() {
		return rs;
	}

	public void setRs(Collection rs) {
		this.rs = rs;
	}

	public String getZxxmm() {
		return zxxmm;
	}

	public void setZxxmm(String zxxmm) {
		this.zxxmm = zxxmm;
	}

	public String getJj() {
		return jj;
	}

	public void setJj(String jj) {
		this.jj = jj;
	}

	public String getZxxzg() {
		return zxxzg;
	}

	public void setZxxzg(String zxxzg) {
		this.zxxzg = zxxzg;
	}

	public String getZxxbh() {
		return zxxbh;
	}

	public void setZxxbh(String zxxbh) {
		this.zxxbh = zxxbh;
	}

	public String getZxxxm() {
		return zxxxm;
	}

	public void setZxxxm(String zxxxm) {
		this.zxxxm = zxxxm;
	}

	public String getXn_id() {
		return xn_id;
	}

	public void setXn_id(String xn_id) {
		this.xn_id = xn_id;
	}

	public String getErrMsg() {
		return errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public String[] getErrMsgs() {
		return errMsgs;
	}

	public void setErrMsgs(String[] errMsgs) {
		this.errMsgs = errMsgs;
	}

	public String[] getCheckVal() {
		return checkVal;
	}

	public void setCheckVal(String[] checkVal) {
		this.checkVal = checkVal;
	}

	public String getQueryequals_bmdm() {
		return queryequals_bmdm;
	}

	public void setQueryequals_bmdm(String queryequals_bmdm) {
		this.queryequals_bmdm = queryequals_bmdm;
	}

	public String getQuerylike_zgh() {
		return querylike_zgh;
	}

	public void setQuerylike_zgh(String querylike_zgh) {
		this.querylike_zgh = querylike_zgh;
	}

	public String getQuerylike_xm() {
		return querylike_xm;
	}

	public void setQuerylike_xm(String querylike_xm) {
		this.querylike_xm = querylike_xm;
	}

	public String getXm() {
		return xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	public String getZgh() {
		return zgh;
	}

	public void setZgh(String zgh) {
		this.zgh = zgh;
	}

	public String getBmdm() {
		return bmdm;
	}

	public void setBmdm(String bmdm) {
		this.bmdm = bmdm;
	}

	public Pages getPages() {
		return pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	public String getFdyxx() {
		return fdyxx;
	}

	public void setFdyxx(String fdyxx) {
		this.fdyxx = fdyxx;
	}

	public String getPpzxs() {
		return ppzxs;
	}

	public void setPpzxs(String ppzxs) {
		this.ppzxs = ppzxs;
	}

	public String getZxsxx() {
		return zxsxx;
	}

	public void setZxsxx(String zxsxx) {
		this.zxsxx = zxsxx;
	}

	public String getPpzxsxx() {
		return ppzxsxx;
	}

	public void setPpzxsxx(String ppzxsxx) {
		this.ppzxsxx = ppzxsxx;
	}

	public String getZxszc() {
		return zxszc;
	}

	public void setZxszc(String zxszc) {
		this.zxszc = zxszc;
	}
}