/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xtwh.comm.gwsz;

import org.apache.struts.action.ActionForm;

import xgxt.form.User;
import xgxt.utils.Pages;

/**
 * MyEclipse Struts Creation date: 03-25-2011
 * 
 * XDoclet definition:
 * 
 * @struts.form name="xtwhGwszForm" author qlj
 */
public class XtwhGwszForm extends ActionForm {
	
	private User user;

	private String xtgwmc;

	private String sfqy;

	private String lrr;

	private String lrsj;

	private String kssj;

	private String jssj;
	
	private String gwsm;

	private String querylike_xtgwmc;

	private String queryequals_sfqy;

	private String querylike_lrr;

	private String queryequals_lrsj;
	
	private String save_gwsm;

	private String save_xtgwmc;

	private String save_sfqy;

	private String save_lrr;

	private String save_lrsj;

	private Pages pages = new Pages();

	public Pages getPages() {
		return pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	public String getXtgwmc() {
		return xtgwmc;
	}

	public void setXtgwmc(String xtgwmc) {
		this.xtgwmc = xtgwmc;
	}

	public String getJssj() {
		return jssj;
	}

	public void setJssj(String jssj) {
		this.jssj = jssj;
	}

	public String getKssj() {
		return kssj;
	}

	public void setKssj(String kssj) {
		this.kssj = kssj;
	}

	public String getLrr() {
		return lrr;
	}

	public void setLrr(String lrr) {
		this.lrr = lrr;
	}

	public String getLrsj() {
		return lrsj;
	}

	public void setLrsj(String lrsj) {
		this.lrsj = lrsj;
	}

	public String getQueryequals_lrsj() {
		return queryequals_lrsj;
	}

	public void setQueryequals_lrsj(String queryequals_lrsj) {
		this.queryequals_lrsj = queryequals_lrsj;
	}

	public String getQueryequals_sfqy() {
		return queryequals_sfqy;
	}

	public void setQueryequals_sfkj(String queryequals_sfqy) {
		this.queryequals_sfqy = queryequals_sfqy;
	}

	public String getQuerylike_xtgwmc() {
		return querylike_xtgwmc;
	}

	public void setQuerylike_xtgwmc(String querylike_xtgwmc) {
		this.querylike_xtgwmc = querylike_xtgwmc;
	}

	public String getQuerylike_lrr() {
		return querylike_lrr;
	}

	public void setQuerylike_lrr(String querylike_lrr) {
		this.querylike_lrr = querylike_lrr;
	}

	public String getSave_xtgwmc() {
		return save_xtgwmc;
	}

	public void setSave_xtgwmc(String save_xtgwmc) {
		this.save_xtgwmc = save_xtgwmc;
	}

	public String getSave_lrr() {
		return save_lrr;
	}

	public void setSave_lrr(String save_lrr) {
		this.save_lrr = save_lrr;
	}

	public String getSave_lrsj() {
		return save_lrsj;
	}

	public void setSave_lrsj(String save_lrsj) {
		this.save_lrsj = save_lrsj;
	}

	public String getSave_sfqy() {
		return save_sfqy;
	}

	public void setSave_sfqy(String save_sfqy) {
		this.save_sfqy = save_sfqy;
	}

	public String getSfqy() {
		return sfqy;
	}

	public void setSfqy(String sfqy) {
		this.sfqy = sfqy;
	}

	public String getGwsm() {
		return gwsm;
	}

	public void setGwsm(String gwsm) {
		this.gwsm = gwsm;
	}

	public String getSave_gwsm() {
		return save_gwsm;
	}

	public void setSave_gwsm(String save_gwsm) {
		this.save_gwsm = save_gwsm;
	}

	public void setQueryequals_sfqy(String queryequals_sfqy) {
		this.queryequals_sfqy = queryequals_sfqy;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}