/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.pjpy.comm.pjpy.xmsz;

import org.apache.struts.action.ActionForm;

import xgxt.utils.Pages;

/**
 * MyEclipse Struts Creation date: 02-16-2011
 * 
 * XDoclet definition:
 * 
 * @struts.form name="pjpyXmszForm"
 */
public class PjpyXmszForm extends ActionForm {

	private static final long serialVersionUID = 1L;

	private Pages pages = new Pages();
	
	private String[]primarykey_cbv;

	private String rssx; // 人数上限

	private String kzjb; // 控制级别

	private String zjtg; // 直接通过

	private String lcid; // 流程ID

	private String xmsm; // 项目说明

	private String sqfs; // 申请方式

	private String pjxq; // 评奖学期
	
	private String pjxqmc;//评奖学期名称

	private String xmmc; // 项目名称

	private String sjje; // 涉及金额

	private String xmje; // 项目金额

	private String rssz; // 人数设置

	private String pjxn; // 评奖学年

	private String pjnd; // 评奖年度

	private String sqzq; // 申请周期

	private String qztj; // 前置条件

	private String xmlx; // 项目类型

	private String ywmc; // 英文名称

	private String xmdm; // 项目代码

	private String kzfw; // 控制范围
	
	private String[] xmdms; //项目代码 

	private String[] sfqy; // 是否启用

	private String xmfw; // 项目范围

	private String xmxz; // 项目性质

	private String sjkz; // 时间控制

	private String sfsh; // 是否审核
	
	private String xssx; // 显示顺序

	// =================保存字段===========================
	private String save_qztj; // 前置条件

	private String save_pjxn; // 评奖学年

	private String save_xmxz; // 项目性质

	private String save_sfqy; // 是否启用

	private String save_pjxq; // 评奖学期

	private String save_sjkz; // 时间控制

	private String save_sfsh; // 是否审核

	private String save_xmsm; // 项目说明

	private String save_xmmc; // 项目名称

	private String save_ywmc; // 英文名称

	private String save_xmdm; // 项目代码

	private String save_rssx; // 人数上限

	private String save_xmfw; // 项目范围

	private String save_sqfs; // 申请方式

	private String save_xmje; // 项目金额

	private String save_rssz; // 人数设置

	private String save_kzjb; // 控制级别

	private String save_kzfw ="bj"; // 控制范围

	private String save_zjtg; // 直接通过

	private String save_xmlx; // 项目类型

	private String save_sjje; // 涉及金额

	private String save_sqzq; // 申请周期

	private String save_lcid; // 流程ID

	private String save_pjnd; // 评奖年度
	
	private String save_xssx; // 显示顺序

	// ===================end============================
	
	// =================查询字段===========================
	private String queryequals_xmje; // 项目金额

	private String queryequals_rssx; // 人数上限

	private String queryequals_sjje; // 涉及金额

	private String queryequals_sfqy; // 是否启用

	private String queryequals_lcid; // 流程ID

	private String queryequals_pjxn; // 评奖学年

	private String queryequals_sqfs; // 申请方式

	private String queryequals_kzfw; // 控制范围

	private String queryequals_xmfw; // 项目范围

	private String queryequals_sjkz; // 时间控制

	private String queryequals_pjxq; // 评奖学期

	private String querylike_ywmc; // 英文名称

	private String queryequals_kzjb; // 控制级别

	private String queryequals_zjtg; // 直接通过

	private String querylike_xmdm; // 项目代码

	private String queryequals_sqzq; // 申请周期

	private String queryequals_xmsm; // 项目说明

	private String queryequals_pjnd; // 评奖年度

	private String queryequals_qztj; // 前置条件

	private String queryequals_sfsh; // 是否审核

	private String queryequals_xmlx; // 项目类型

	private String querylike_xmmc; // 项目名称

	private String queryequals_rssz; // 人数设置

	private String queryequals_xmxz; // 项目性质
	
	private String select_xn;//项目复制学年
	
	private String select_xq;//项目复制学期
	
	private String select_nd;//项目复制年度	

	public String getKzfw() {
		return kzfw;
	}

	public void setKzfw(String kzfw) {
		this.kzfw = kzfw;
	}

	public String getKzjb() {
		return kzjb;
	}

	public void setKzjb(String kzjb) {
		this.kzjb = kzjb;
	}

	public String getLcid() {
		return lcid;
	}

	public void setLcid(String lcid) {
		this.lcid = lcid;
	}

	public Pages getPages() {
		return pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	public String getPjnd() {
		return pjnd;
	}

	public void setPjnd(String pjnd) {
		this.pjnd = pjnd;
	}

	public String getPjxn() {
		return pjxn;
	}

	public void setPjxn(String pjxn) {
		this.pjxn = pjxn;
	}

	public String getPjxq() {
		return pjxq;
	}

	public void setPjxq(String pjxq) {
		this.pjxq = pjxq;
	}

	public String getQztj() {
		return qztj;
	}

	public void setQztj(String qztj) {
		this.qztj = qztj;
	}

	public String getRssx() {
		return rssx;
	}

	public void setRssx(String rssx) {
		this.rssx = rssx;
	}

	public String getRssz() {
		return rssz;
	}

	public void setRssz(String rssz) {
		this.rssz = rssz;
	}

	public String[] getSfqy() {
		return sfqy;
	}

	public void setSfqy(String[] sfqy) {
		this.sfqy = sfqy;
	}

	public String getSfsh() {
		return sfsh;
	}

	public void setSfsh(String sfsh) {
		this.sfsh = sfsh;
	}

	public String getSjje() {
		return sjje;
	}

	public void setSjje(String sjje) {
		this.sjje = sjje;
	}

	public String getSjkz() {
		return sjkz;
	}

	public void setSjkz(String sjkz) {
		this.sjkz = sjkz;
	}

	public String getSqfs() {
		return sqfs;
	}

	public void setSqfs(String sqfs) {
		this.sqfs = sqfs;
	}

	public String getSqzq() {
		return sqzq;
	}

	public void setSqzq(String sqzq) {
		this.sqzq = sqzq;
	}
	
	public String getXmdm() {
		return xmdm;
	}

	public void setXmdm(String xmdm) {
		this.xmdm = xmdm;
	}

	public String getXmfw() {
		return xmfw;
	}

	public void setXmfw(String xmfw) {
		this.xmfw = xmfw;
	}

	public String getXmje() {
		return xmje;
	}

	public void setXmje(String xmje) {
		this.xmje = xmje;
	}

	public String getXmlx() {
		return xmlx;
	}

	public void setXmlx(String xmlx) {
		this.xmlx = xmlx;
	}

	public String getXmmc() {
		return xmmc;
	}

	public void setXmmc(String xmmc) {
		this.xmmc = xmmc;
	}

	public String getXmsm() {
		return xmsm;
	}

	public void setXmsm(String xmsm) {
		this.xmsm = xmsm;
	}

	public String getXmxz() {
		return xmxz;
	}

	public void setXmxz(String xmxz) {
		this.xmxz = xmxz;
	}

	public String getYwmc() {
		return ywmc;
	}

	public void setYwmc(String ywmc) {
		this.ywmc = ywmc;
	}

	public String getZjtg() {
		return zjtg;
	}

	public void setZjtg(String zjtg) {
		this.zjtg = zjtg;
	}

	public String getSave_kzfw() {
		return save_kzfw;
	}

	public void setSave_kzfw(String save_kzfw) {
		this.save_kzfw = save_kzfw;
	}

	public String getSave_kzjb() {
		return save_kzjb;
	}

	public void setSave_kzjb(String save_kzjb) {
		this.save_kzjb = save_kzjb;
	}

	public String getSave_lcid() {
		return save_lcid;
	}

	public void setSave_lcid(String save_lcid) {
		this.save_lcid = save_lcid;
	}

	public String getSave_pjnd() {
		return save_pjnd;
	}

	public void setSave_pjnd(String save_pjnd) {
		this.save_pjnd = save_pjnd;
	}

	public String getSave_pjxn() {
		return save_pjxn;
	}

	public void setSave_pjxn(String save_pjxn) {
		this.save_pjxn = save_pjxn;
	}

	public String getSave_pjxq() {
		return save_pjxq;
	}

	public void setSave_pjxq(String save_pjxq) {
		this.save_pjxq = save_pjxq;
	}

	public String getSave_qztj() {
		return save_qztj;
	}

	public void setSave_qztj(String save_qztj) {
		this.save_qztj = save_qztj;
	}

	public String getSave_rssx() {
		return save_rssx;
	}

	public void setSave_rssx(String save_rssx) {
		this.save_rssx = save_rssx;
	}

	public String getSave_rssz() {
		return save_rssz;
	}

	public void setSave_rssz(String save_rssz) {
		this.save_rssz = save_rssz;
	}

	public String getSave_sfqy() {
		return save_sfqy;
	}

	public void setSave_sfqy(String save_sfqy) {
		this.save_sfqy = save_sfqy;
	}

	public String getSave_sfsh() {
		return save_sfsh;
	}

	public void setSave_sfsh(String save_sfsh) {
		this.save_sfsh = save_sfsh;
	}

	public String getSave_sjje() {
		return save_sjje;
	}

	public void setSave_sjje(String save_sjje) {
		this.save_sjje = save_sjje;
	}

	public String getSave_sjkz() {
		return save_sjkz;
	}

	public void setSave_sjkz(String save_sjkz) {
		this.save_sjkz = save_sjkz;
	}

	public String getSave_sqfs() {
		return save_sqfs;
	}

	public void setSave_sqfs(String save_sqfs) {
		this.save_sqfs = save_sqfs;
	}

	public String getSave_sqzq() {
		return save_sqzq;
	}

	public void setSave_sqzq(String save_sqzq) {
		this.save_sqzq = save_sqzq;
	}

	public String getSave_xmdm() {
		return save_xmdm;
	}

	public void setSave_xmdm(String save_xmdm) {
		this.save_xmdm = save_xmdm;
	}

	public String getSave_xmfw() {
		return save_xmfw;
	}

	public void setSave_xmfw(String save_xmfw) {
		this.save_xmfw = save_xmfw;
	}

	public String getSave_xmje() {
		return save_xmje;
	}

	public void setSave_xmje(String save_xmje) {
		this.save_xmje = save_xmje;
	}

	public String getSave_xmlx() {
		return save_xmlx;
	}

	public void setSave_xmlx(String save_xmlx) {
		this.save_xmlx = save_xmlx;
	}

	public String getSave_xmmc() {
		return save_xmmc;
	}

	public void setSave_xmmc(String save_xmmc) {
		this.save_xmmc = save_xmmc;
	}

	public String getSave_xmsm() {
		return save_xmsm;
	}

	public void setSave_xmsm(String save_xmsm) {
		this.save_xmsm = save_xmsm;
	}

	public String getSave_xmxz() {
		return save_xmxz;
	}

	public void setSave_xmxz(String save_xmxz) {
		this.save_xmxz = save_xmxz;
	}

	public String getSave_ywmc() {
		return save_ywmc;
	}

	public void setSave_ywmc(String save_ywmc) {
		this.save_ywmc = save_ywmc;
	}

	public String getSave_zjtg() {
		return save_zjtg;
	}

	public void setSave_zjtg(String save_zjtg) {
		this.save_zjtg = save_zjtg;
	}

	public String getQueryequals_kzfw() {
		return queryequals_kzfw;
	}

	public void setQueryequals_kzfw(String queryequals_kzfw) {
		this.queryequals_kzfw = queryequals_kzfw;
	}

	public String getQueryequals_kzjb() {
		return queryequals_kzjb;
	}

	public void setQueryequals_kzjb(String queryequals_kzjb) {
		this.queryequals_kzjb = queryequals_kzjb;
	}

	public String getQueryequals_lcid() {
		return queryequals_lcid;
	}

	public void setQueryequals_lcid(String queryequals_lcid) {
		this.queryequals_lcid = queryequals_lcid;
	}

	public String getQueryequals_pjnd() {
		return queryequals_pjnd;
	}

	public void setQueryequals_pjnd(String queryequals_pjnd) {
		this.queryequals_pjnd = queryequals_pjnd;
	}

	public String getQueryequals_pjxn() {
		return queryequals_pjxn;
	}

	public void setQueryequals_pjxn(String queryequals_pjxn) {
		this.queryequals_pjxn = queryequals_pjxn;
	}

	public String getQueryequals_pjxq() {
		return queryequals_pjxq;
	}

	public void setQueryequals_pjxq(String queryequals_pjxq) {
		this.queryequals_pjxq = queryequals_pjxq;
	}

	public String getQueryequals_qztj() {
		return queryequals_qztj;
	}

	public void setQueryequals_qztj(String queryequals_qztj) {
		this.queryequals_qztj = queryequals_qztj;
	}

	public String getQueryequals_rssx() {
		return queryequals_rssx;
	}

	public void setQueryequals_rssx(String queryequals_rssx) {
		this.queryequals_rssx = queryequals_rssx;
	}

	public String getQueryequals_rssz() {
		return queryequals_rssz;
	}

	public void setQueryequals_rssz(String queryequals_rssz) {
		this.queryequals_rssz = queryequals_rssz;
	}

	public String getQueryequals_sfqy() {
		return queryequals_sfqy;
	}

	public void setQueryequals_sfqy(String queryequals_sfqy) {
		this.queryequals_sfqy = queryequals_sfqy;
	}

	public String getQueryequals_sfsh() {
		return queryequals_sfsh;
	}

	public void setQueryequals_sfsh(String queryequals_sfsh) {
		this.queryequals_sfsh = queryequals_sfsh;
	}

	public String getQueryequals_sjje() {
		return queryequals_sjje;
	}

	public void setQueryequals_sjje(String queryequals_sjje) {
		this.queryequals_sjje = queryequals_sjje;
	}

	public String getQueryequals_sjkz() {
		return queryequals_sjkz;
	}

	public void setQueryequals_sjkz(String queryequals_sjkz) {
		this.queryequals_sjkz = queryequals_sjkz;
	}

	public String getQueryequals_sqfs() {
		return queryequals_sqfs;
	}

	public void setQueryequals_sqfs(String queryequals_sqfs) {
		this.queryequals_sqfs = queryequals_sqfs;
	}

	public String getQueryequals_sqzq() {
		return queryequals_sqzq;
	}

	public void setQueryequals_sqzq(String queryequals_sqzq) {
		this.queryequals_sqzq = queryequals_sqzq;
	}

	public String getQueryequals_xmfw() {
		return queryequals_xmfw;
	}

	public void setQueryequals_xmfw(String queryequals_xmfw) {
		this.queryequals_xmfw = queryequals_xmfw;
	}

	public String getQueryequals_xmje() {
		return queryequals_xmje;
	}

	public void setQueryequals_xmje(String queryequals_xmje) {
		this.queryequals_xmje = queryequals_xmje;
	}

	public String getQueryequals_xmsm() {
		return queryequals_xmsm;
	}

	public void setQueryequals_xmsm(String queryequals_xmsm) {
		this.queryequals_xmsm = queryequals_xmsm;
	}

	public String getQueryequals_xmxz() {
		return queryequals_xmxz;
	}

	public void setQueryequals_xmxz(String queryequals_xmxz) {
		this.queryequals_xmxz = queryequals_xmxz;
	}

	public String getQueryequals_zjtg() {
		return queryequals_zjtg;
	}

	public void setQueryequals_zjtg(String queryequals_zjtg) {
		this.queryequals_zjtg = queryequals_zjtg;
	}

	public String getQuerylike_xmmc() {
		return querylike_xmmc;
	}

	public void setQuerylike_xmmc(String querylike_xmmc) {
		this.querylike_xmmc = querylike_xmmc;
	}

	public String getQuerylike_ywmc() {
		return querylike_ywmc;
	}

	public void setQuerylike_ywmc(String querylike_ywmc) {
		this.querylike_ywmc = querylike_ywmc;
	}

	public String getQueryequals_xmlx() {
		return queryequals_xmlx;
	}

	public void setQueryequals_xmlx(String queryequals_xmlx) {
		this.queryequals_xmlx = queryequals_xmlx;
	}

	public String getQuerylike_xmdm() {
		return querylike_xmdm;
	}

	public void setQuerylike_xmdm(String querylike_xmdm) {
		this.querylike_xmdm = querylike_xmdm;
	}

	public String getSave_xssx() {
		return save_xssx;
	}

	public void setSave_xssx(String save_xssx) {
		this.save_xssx = save_xssx;
	}

	public String getXssx() {
		return xssx;
	}

	public void setXssx(String xssx) {
		this.xssx = xssx;
	}

	public String[] getXmdms() {
		return xmdms;
	}

	public void setXmdms(String[] xmdms) {
		this.xmdms = xmdms;
	}

	public String[] getPrimarykey_cbv() {
		return primarykey_cbv;
	}

	public void setPrimarykey_cbv(String[] primarykey_cbv) {
		this.primarykey_cbv = primarykey_cbv;
	}

	public String getPjxqmc() {
		return pjxqmc;
	}

	public void setPjxqmc(String pjxqmc) {
		this.pjxqmc = pjxqmc;
	}

	public String getSelect_nd() {
		return select_nd;
	}

	public void setSelect_nd(String select_nd) {
		this.select_nd = select_nd;
	}

	public String getSelect_xn() {
		return select_xn;
	}

	public void setSelect_xn(String select_xn) {
		this.select_xn = select_xn;
	}

	public String getSelect_xq() {
		return select_xq;
	}

	public void setSelect_xq(String select_xq) {
		this.select_xq = select_xq;
	}
}