/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.qgzx.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

import xgxt.utils.Pages;

public class QgzxGwfbForm extends ActionForm {
	private static final long serialVersionUID = 1L;
	
	Pages pages = new Pages();
	private FormFile uploadFile;
	private String pk;           //主键
	private String[] pkV;        //主键值
	private String xydm;         //学院代码
	private String zydm;         //专业代码
	private String bjdm;         //班级代码
	private String xymc;         //学院名称
	private String zymc;         //专业名称
	private String bjmc;         //班级名称
	private String xh;           //学号
	private String xb;           //性别
	private String xm;           //姓名
	private String nj;           //年级
	private String gwxz;         //岗位性质
	private String xn;           //学年
	private String xq;           //学期
	private String nd;           //年度
	private String xmdm;         //项目代码
	private String gwdm;         //岗位代码
	private String gwsbsj;       //岗位上报时间
	private String cxfs;         //
	private String yrdwdm;       //用人单位代码
	private String hblb;         //划拨类别
	private String yf;           //月份
	private String pkValue;      //主键值
	private String jsjsp;        //计算机水平
	private String yhtc;         //特长
	private String sffcfp="1";   //是否服从分派
	private String ldmc;         //楼栋名称
	private String mqqgzxqk;     //目前勤工助学情况
	private String kssj;         //开始时间
	private String jssj;         //结束时间
	private String bz;           //备注
	private String gzjl;         //工作经历
	private String xssq;         //申请理由
	private String rq;           //日期
	private String gzkssj;       //工作开始时间
	private String gzjssj;       //工作结束时间
	private String gznr;         //工作内容
	private String zgzsj;        //总工作时间
	private String ygzsj;        //月工作时间
	private String ffcjje;       //发放酬金金额
	private String ffsj;         //发放时间
	private String ffsjks;       //发放时间开始
	private String ffsjjs;       //发放时间结束
	private String userName;     //用户名
	private String userType;     //用户类型
	private String fflx;         //发放类型
	private String xxyj;//学校审核
	private String xyyj;//学院审核
	private String fdyyj;//辅导员审核
	private String xxsh;//学校审核
	private String queryequals_xn;
	private String queryequals_nd;
	private String queryequals_xueqi;
	private String queryequals_gwdm;
	private String queryequals_gwxz;
	
	private String save_xq;        //校区
	private String save_gwdm;      //岗位名称
	private String save_gwxz;
	private String save_sqdw;
	private String save_xn;
	private String save_xueqi;     //学期
	private String save_nd;
	private String save_gzksrq;
	private String save_gzjsrq;
	private String save_xyrs;
	private String save_xyknsrs;
	private String save_jcfs;
	private String save_jybcbz;	
	private String save_lxdh;
	private String save_gzsj;
	private String save_gznr;
	private String save_gzdd;
	private String save_gwtsyq;
	private String save_ryyq;
	private String save_sqbg;
	private String save_sqdwyj;
	private String save_bz;
	private String save_mssj;
	private String save_msdd;
	
	

	public String getQueryequals_gwxz() {
		return queryequals_gwxz;
	}

	public void setQueryequals_gwxz(String queryequals_gwxz) {
		this.queryequals_gwxz = queryequals_gwxz;
	}

	public Pages getPages() {
		return pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	public String getJssj() {
		return jssj;
	}

	public void setJssj(String jssj) {
		this.jssj = jssj;
	}

	public String getKssj() {
		return kssj;
	}

	public void setKssj(String kssj) {
		this.kssj = kssj;
	}

	public String getMqqgzxqk() {
		return mqqgzxqk;
	}

	public void setMqqgzxqk(String mqqgzxqk) {
		this.mqqgzxqk = mqqgzxqk;
	}

	public String getLdmc() {
		return ldmc;
	}

	public void setLdmc(String ldmc) {
		this.ldmc = ldmc;
	}

	public String getXb() {
		return xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	public String getJsjsp() {
		return jsjsp;
	}

	public void setJsjsp(String jsjsp) {
		this.jsjsp = jsjsp;
	}

	public String getSffcfp() {
		return sffcfp;
	}

	public void setSffcfp(String sffcfp) {
		this.sffcfp = sffcfp;
	}

	public String getYhtc() {
		return yhtc;
	}

	public void setTc(String yhtc) {
		this.yhtc = yhtc;
	}

	public String getPkValue() {
		return pkValue;
	}

	public void setPkValue(String pkValue) {
		this.pkValue = pkValue;
	}

	public String getYf() {
		return yf;
	}

	public void setYf(String yf) {
		this.yf = yf;
	}

	public String getHblb() {
		return hblb;
	}

	public void setHblb(String hblb) {
		this.hblb = hblb;
	}

	public String getYrdwdm() {
		return yrdwdm;
	}

	public void setYrdwdm(String yrdwdm) {
		this.yrdwdm = yrdwdm;
	}

	public String getCxfs() {
		return cxfs;
	}

	public void setCxfs(String cxfs) {
		this.cxfs = cxfs;
	}

	public String getGwdm() {
		return gwdm;
	}

	public void setGwdm(String gwdm) {
		this.gwdm = gwdm;
	}

	public String getXmdm() {
		return xmdm;
	}

	public void setXmdm(String xmdm) {
		this.xmdm = xmdm;
	}

	public String getNd() {
		return nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getXn() {
		return xn;
	}

	public void setXn(String xn) {
		this.xn = xn;
	}

	public String getXq() {
		return xq;
	}

	public void setXq(String xq) {
		this.xq = xq;
	}

	public String getGwxz() {
		return gwxz;
	}

	public void setGwxz(String gwxz) {
		this.gwxz = gwxz;
	}

	public String getBjdm() {
		return bjdm;
	}

	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}

	public String getNj() {
		return nj;
	}

	public void setNj(String nj) {
		this.nj = nj;
	}

	public String getXh() {
		return xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public String getXm() {
		return xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	public String getXydm() {
		return xydm;
	}

	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	public String getZydm() {
		return zydm;
	}

	public void setZydm(String zydm) {
		this.zydm = zydm;
	}

	public String getBjmc() {
		return bjmc;
	}

	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}

	public String getXymc() {
		return xymc;
	}

	public void setXymc(String xymc) {
		this.xymc = xymc;
	}

	public String getZymc() {
		return zymc;
	}

	public void setZymc(String zymc) {
		this.zymc = zymc;
	}

	public String getPk() {
		return pk;
	}

	public void setPk(String pk) {
		this.pk = pk;
	}

	public void setYhtc(String yhtc) {
		this.yhtc = yhtc;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getGzjl() {
		return gzjl;
	}

	public void setGzjl(String gzjl) {
		this.gzjl = gzjl;
	}

	public String getXssq() {
		return xssq;
	}

	public void setXssq(String xssq) {
		this.xssq = xssq;
	}

	public String getRq() {
		return rq;
	}

	public void setRq(String rq) {
		this.rq = rq;
	}

	public String getGzkssj() {
		return gzkssj;
	}

	public void setGzkssj(String gzkssj) {
		this.gzkssj = gzkssj;
	}

	public String getGzjssj() {
		return gzjssj;
	}

	public void setGzjssj(String gzjssj) {
		this.gzjssj = gzjssj;
	}

	public String getGznr() {
		return gznr;
	}

	public void setGznr(String gznr) {
		this.gznr = gznr;
	}

	public String getZgzsj() {
		return zgzsj;
	}

	public void setZgzsj(String zgzsj) {
		this.zgzsj = zgzsj;
	}

	public String getYgzsj() {
		return ygzsj;
	}

	public void setYgzsj(String ygzsj) {
		this.ygzsj = ygzsj;
	}

	public String getFfcjje() {
		return ffcjje;
	}

	public void setFfcjje(String ffcjje) {
		this.ffcjje = ffcjje;
	}

	public String getGwsbsj() {
		return gwsbsj;
	}

	public void setGwsbsj(String gwsbsj) {
		this.gwsbsj = gwsbsj;
	}

	public String[] getPkV() {
		return pkV;
	}

	public void setPkV(String[] pkV) {
		this.pkV = pkV;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFfsj() {
		return ffsj;
	}

	public void setFfsj(String ffsj) {
		this.ffsj = ffsj;
	}

	public String getFfsjks() {
		return ffsjks;
	}

	public void setFfsjks(String ffsjks) {
		this.ffsjks = ffsjks;
	}

	public String getFfsjjs() {
		return ffsjjs;
	}

	public void setFfsjjs(String ffsjjs) {
		this.ffsjjs = ffsjjs;
	}


	public String getFflx() {
		return fflx;
	}

	public void setFflx(String fflx) {
		this.fflx = fflx;
	}


	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public FormFile getUploadFile() {
		return uploadFile;
	}

	public void setUploadFile(FormFile uploadFile) {
		this.uploadFile = uploadFile;
	}

	public String getXxyj() {
		return xxyj;
	}

	public void setXxyj(String xxyj) {
		this.xxyj = xxyj;
	}

	public String getXyyj() {
		return xyyj;
	}

	public void setXyyj(String xyyj) {
		this.xyyj = xyyj;
	}

	public String getFdyyj() {
		return fdyyj;
	}

	public void setFdyyj(String fdyyj) {
		this.fdyyj = fdyyj;
	}

	public String getXxsh() {
		return xxsh;
	}

	public void setXxsh(String xxsh) {
		this.xxsh = xxsh;
	}

	public String getQueryequals_xn() {
		return queryequals_xn;
	}

	public void setQueryequals_xn(String queryequals_xn) {
		this.queryequals_xn = queryequals_xn;
	}

	public String getQueryequals_nd() {
		return queryequals_nd;
	}

	public void setQueryequals_nd(String queryequals_nd) {
		this.queryequals_nd = queryequals_nd;
	}

	public String getQueryequals_xueqi() {
		return queryequals_xueqi;
	}

	public void setQueryequals_xueqi(String queryequals_xueqi) {
		this.queryequals_xueqi = queryequals_xueqi;
	}

	public String getQueryequals_gwdm() {
		return queryequals_gwdm;
	}

	public void setQueryequals_gwdm(String queryequals_gwdm) {
		this.queryequals_gwdm = queryequals_gwdm;
	}

	public String getSave_xq() {
		return save_xq;
	}

	public void setSave_xq(String save_xq) {
		this.save_xq = save_xq;
	}

	public String getSave_gwdm() {
		return save_gwdm;
	}

	public void setSave_gwdm(String save_gwdm) {
		this.save_gwdm = save_gwdm;
	}

	public String getSave_gwxz() {
		return save_gwxz;
	}

	public void setSave_gwxz(String save_gwxz) {
		this.save_gwxz = save_gwxz;
	}

	public String getSave_sqdw() {
		return save_sqdw;
	}

	public void setSave_sqdw(String save_sqdw) {
		this.save_sqdw = save_sqdw;
	}

	public String getSave_xn() {
		return save_xn;
	}

	public void setSave_xn(String save_xn) {
		this.save_xn = save_xn;
	}

	public String getSave_xueqi() {
		return save_xueqi;
	}

	public void setSave_xueqi(String save_xueqi) {
		this.save_xueqi = save_xueqi;
	}

	public String getSave_nd() {
		return save_nd;
	}

	public void setSave_nd(String save_nd) {
		this.save_nd = save_nd;
	}

	public String getSave_gzksrq() {
		return save_gzksrq;
	}

	public void setSave_gzksrq(String save_gzksrq) {
		this.save_gzksrq = save_gzksrq;
	}

	public String getSave_gzjsrq() {
		return save_gzjsrq;
	}

	public void setSave_gzjsrq(String save_gzjsrq) {
		this.save_gzjsrq = save_gzjsrq;
	}

	public String getSave_xyrs() {
		return save_xyrs;
	}

	public void setSave_xyrs(String save_xyrs) {
		this.save_xyrs = save_xyrs;
	}

	public String getSave_xyknsrs() {
		return save_xyknsrs;
	}

	public void setSave_xyknsrs(String save_xyknsrs) {
		this.save_xyknsrs = save_xyknsrs;
	}

	public String getSave_jcfs() {
		return save_jcfs;
	}

	public void setSave_jcfs(String save_jcfs) {
		this.save_jcfs = save_jcfs;
	}

	public String getSave_jybcbz() {
		return save_jybcbz;
	}

	public void setSave_jybcbz(String save_jybcbz) {
		this.save_jybcbz = save_jybcbz;
	}

	public String getSave_lxdh() {
		return save_lxdh;
	}

	public void setSave_lxdh(String save_lxdh) {
		this.save_lxdh = save_lxdh;
	}

	public String getSave_gzsj() {
		return save_gzsj;
	}

	public void setSave_gzsj(String save_gzsj) {
		this.save_gzsj = save_gzsj;
	}

	public String getSave_gznr() {
		return save_gznr;
	}

	public void setSave_gznr(String save_gznr) {
		this.save_gznr = save_gznr;
	}

	public String getSave_gzdd() {
		return save_gzdd;
	}

	public void setSave_gzdd(String save_gzdd) {
		this.save_gzdd = save_gzdd;
	}

	public String getSave_gwtsyq() {
		return save_gwtsyq;
	}

	public void setSave_gwtsyq(String save_gwtsyq) {
		this.save_gwtsyq = save_gwtsyq;
	}

	public String getSave_ryyq() {
		return save_ryyq;
	}

	public void setSave_ryyq(String save_ryyq) {
		this.save_ryyq = save_ryyq;
	}

	public String getSave_sqbg() {
		return save_sqbg;
	}

	public void setSave_sqbg(String save_sqbg) {
		this.save_sqbg = save_sqbg;
	}

	public String getSave_sqdwyj() {
		return save_sqdwyj;
	}

	public void setSave_sqdwyj(String save_sqdwyj) {
		this.save_sqdwyj = save_sqdwyj;
	}

	public String getSave_bz() {
		return save_bz;
	}

	public void setSave_bz(String save_bz) {
		this.save_bz = save_bz;
	}

	public String getSave_mssj() {
		return save_mssj;
	}

	public void setSave_mssj(String save_mssj) {
		this.save_mssj = save_mssj;
	}

	public String getSave_msdd() {
		return save_msdd;
	}

	public void setSave_msdd(String save_msdd) {
		this.save_msdd = save_msdd;
	}		
}