/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.gygl.cwgl;

import java.util.List;

import xgxt.gygl.GyglCommForm;
import xgxt.utils.Pages;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2011
 * 
 * XDoclet definition:
 * @struts.form name="gyglCwglForm"
 */
public class GyglCwglForm extends GyglCommForm{
	private static final long serialVersionUID = 1L;
	
	private String[]ydxh;//异动学号;

	private String fpdx;// '分配对象';
	
	private String pkValue;
	
	private String pk;
	
	private String []pkvArr;
	
	private String []checkVal;
	
	private String []xhArr;
	
	private String []lddmArr;
	
	private String []cwhArr;
	
	private String []qshArr;
	
	private String []csArr;
	
	private String query;
	
	private List colList;
	
	private String xh;

	private String bmdm;
	
	private String qsh;
	
	private String lddm;
	
	private String cs;
	
	private String nj;
	
	private String message;
	
	private String []cwfp;//床位分配
	
	private String[] xsxhArr;
	
	public String[] getXsxhArr() {
		return xsxhArr;
	}

	public void setXsxhArr(String[] xsxhArr) {
		this.xsxhArr = xsxhArr;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getNj() {
		return nj;
	}

	public void setNj(String nj) {
		this.nj = nj;
	}

	public String getBmdm() {
		return bmdm;
	}

	public void setBmdm(String bmdm) {
		this.bmdm = bmdm;
	}

	public String getCs() {
		return cs;
	}

	public void setCs(String cs) {
		this.cs = cs;
	}

	public String getFpdx() {
		return fpdx;
	}

	public void setFpdx(String fpdx) {
		this.fpdx = fpdx;
	}

	public String getLddm() {
		return lddm;
	}

	public void setLddm(String lddm) {
		this.lddm = lddm;
	}

	public String[] getPkvArr() {
		return pkvArr;
	}

	public void setPkvArr(String[] pkvArr) {
		this.pkvArr = pkvArr;
	}

	public String getQsh() {
		return qsh;
	}

	public void setQsh(String qsh) {
		this.qsh = qsh;
	}

	public List getColList() {
		return colList;
	}

	public void setColList(List colList) {
		this.colList = colList;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getPkValue() {
		return pkValue;
	}

	public void setPkValue(String pkValue) {
		this.pkValue = pkValue;
	}

	public String getXh() {
		return xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public String[] getCsArr() {
		return csArr;
	}

	public void setCsArr(String[] csArr) {
		this.csArr = csArr;
	}

	public String[] getCwhArr() {
		return cwhArr;
	}

	public void setCwhArr(String[] cwhArr) {
		this.cwhArr = cwhArr;
	}

	public String[] getLddmArr() {
		return lddmArr;
	}

	public void setLddmArr(String[] lddmArr) {
		this.lddmArr = lddmArr;
	}

	public String[] getQshArr() {
		return qshArr;
	}

	public void setQshArr(String[] qshArr) {
		this.qshArr = qshArr;
	}

	public String[] getXhArr() {
		return xhArr;
	}

	public void setXhArr(String[] xhArr) {
		this.xhArr = xhArr;
	}

	public String[] getCheckVal() {
		return checkVal;
	}

	public void setCheckVal(String[] checkVal) {
		this.checkVal = checkVal;
	}

	public String getPk() {
		return pk;
	}

	public void setPk(String pk) {
		this.pk = pk;
	}

	public String[] getCwfp() {
		return cwfp;
	}

	public void setCwfp(String[] cwfp) {
		this.cwfp = cwfp;
	}

	public String[] getYdxh() {
		return ydxh;
	}

	public void setYdxh(String[] ydxh) {
		this.ydxh = ydxh;
	}
}