/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xljk.lrh_Util.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import xgxt.base.DealString;

/** 
 * MyEclipse Struts
 * Creation date: 08-25-2007
 * 
 * XDoclet definition:
 * @struts.form name="/lrh_commen_form"
 */
public class lrh_commen_form extends ActionForm {
	/*
	 * Generated Methods
	 */

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	DealString deal = new DealString();
	private String 	 errMsg;
	private String[] errMsgs;
	
	private String userType="";
	private String tableName="";
	private String realTable="";
	private String username="";
	
	private String xh="";
	private String xm="";
	private String xb="";
	private String qsdh="";//寝室电话
	private String zydm="";//专业代码
	private String zymc="";//专业名称
	private String bjdm="";//班级代码
	private String bjmc="";//班级名称
	
	private String sql="";
	private String usersql="";
	
	private String []otherKey={};
	private String []otherKeyValue={};
	
	private String url="";
	
	public void deal_gbk()
	{
		this.userType=DealString.toGBK(userType);
		this.tableName=DealString.toGBK(tableName);
		this.realTable=DealString.toGBK(realTable);
		this.username=DealString.toGBK(username);
		                      
		this.xh=DealString.toGBK(xh);
		this.xm=DealString.toGBK(xm);
		this.xb=DealString.toGBK(xb);
		this.qsdh=DealString.toGBK(qsdh);
		this.zydm =DealString.toGBK(zydm);
		this.zymc=DealString.toGBK(zymc);
		this.bjdm =DealString.toGBK(bjdm);
		this.bjmc=DealString.toGBK(bjmc);
		                      
		this.sql=DealString.toGBK(sql);
		this.usersql=DealString.toGBK(usersql);
		this.url=DealString.toGBK(url);
		this.errMsg=DealString.toGBK(errMsg);
	}
	
	
	public String getBjdm() {
		return bjdm;
	}

	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}

	public String getBjmc() {
		return bjmc;
	}

	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}

	public String getErrMsg() {
		return errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public String[] getErrMsgs() {
		return errMsgs;
	}

	public void setErrMsgs(String[] errMsgs) {
		this.errMsgs = errMsgs;
	}

	public String[] getOtherKey() {
		return otherKey;
	}

	public void setOtherKey(String[] otherKey) {
		this.otherKey = otherKey;
	}

	public String[] getOtherKeyValue() {
		return otherKeyValue;
	}

	public void setOtherKeyValue(String[] otherKeyValue) {
		this.otherKeyValue = otherKeyValue;
	}

	public String getQsdh() {
		return qsdh;
	}

	public void setQsdh(String qsdh) {
		this.qsdh = qsdh;
	}

	public String getRealTable() {
		return realTable;
	}

	public void setRealTable(String realTable) {
		this.realTable = realTable;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsersql() {
		return usersql;
	}

	public void setUsersql(String usersql) {
		this.usersql = usersql;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getXb() {
		return xb;
	}

	public void setXb(String xb) {
		this.xb = xb;
	}

	public String getXh() {
		return xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public String getXm() {
		return xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	public String getZydm() {
		return zydm;
	}

	public void setZydm(String zydm) {
		this.zydm = zydm;
	}

	public String getZymc() {
		return zymc;
	}

	public void setZymc(String zymc) {
		this.zymc = zymc;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}