/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.dtjs.gdby.tyxx;

import org.apache.struts.action.ActionForm;

import xgxt.utils.Pages;

/** 
 * MyEclipse Struts
 * Creation date: 07-28-2010
 * 
 * XDoclet definition:
 * @struts.form name="gdbyTyxxForm"
 */
public class GdbyTyxxForm extends ActionForm {
	
	private String rtdd;     //入团地点
	private String zydm;     //专业代码
	private String []xh;     //学号
	private String rtrq;     //入团日期
	private String hsrhzw;     //何时担任何职务
	private String cjst;     //参加社团
	private String bjdm;     //班级代码
	private String cjshsj;     //参加社会实践
	private String zyzqk;     //职员者的情况记录
	private String cjpxqk;     //参加培训情况
	private String tjyd;     //团籍异动
	private String xydm;     //学院代码
	private String bz;
	private String xm;
	private String xb;
	private String nj;
	private String xymc;
	private String zymc;
	private String bjmc;
	private String sfzj;
	private String[] checkVal;
	private String[] primarykey_cbv;
	
	private String save_xh;     //学号
	private String save_cjst;     //参加社团
	private String save_cjshsj;     //参加社会实践
	private String save_zyzqk;     //职员者的情况记录
	private String save_rtdd;     //入团地点
	private String save_zydm;     //专业代码
	private String save_rtrq;     //入团日期
	private String save_hsrhzw;     //何时担任何职务
	private String save_cjpxqk;     //参加培训情况
	private String save_tjyd;     //团籍异动
	private String save_bjdm;     //班级代码
	private String save_xydm;     //学院代码
	private String save_ydzt;
	private String save_ydlx;
	private String save_bz;
	private String save_ydsj;
	
	private String querylike_xh;
	private String querylike_xm;
	private String queryequals_nj;
	private String queryequals_xydm;
	private String queryequals_zydm;
	private String queryequals_bjdm;
	private String queryequals_sfyyd;
	private String queryequals_ydlxmc;
	private String queryequals_ydzt;
	private String queryequals_checked;
	private Pages pages=new Pages();
	public String getBjdm() {
		return bjdm;
	}
	public void setBjdm(String bjdm) {
		this.bjdm = bjdm;
	}
	public String getCjpxqk() {
		return cjpxqk;
	}
	public void setCjpxqk(String cjpxqk) {
		this.cjpxqk = cjpxqk;
	}
	public String getCjshsj() {
		return cjshsj;
	}
	public void setCjshsj(String cjshsj) {
		this.cjshsj = cjshsj;
	}
	public String getCjst() {
		return cjst;
	}
	public void setCjst(String cjst) {
		this.cjst = cjst;
	}
	public String getHsrhzw() {
		return hsrhzw;
	}
	public void setHsrhzw(String hsrhzw) {
		this.hsrhzw = hsrhzw;
	}
	public String getRtdd() {
		return rtdd;
	}
	public void setRtdd(String rtdd) {
		this.rtdd = rtdd;
	}
	public String getRtrq() {
		return rtrq;
	}
	public void setRtrq(String rtrq) {
		this.rtrq = rtrq;
	}
	public String getSave_bjdm() {
		return save_bjdm;
	}
	public void setSave_bjdm(String save_bjdm) {
		this.save_bjdm = save_bjdm;
	}
	public String getSave_cjpxqk() {
		return save_cjpxqk;
	}
	public void setSave_cjpxqk(String save_cjpxqk) {
		this.save_cjpxqk = save_cjpxqk;
	}
	public String getSave_cjshsj() {
		return save_cjshsj;
	}
	public void setSave_cjshsj(String save_cjshsj) {
		this.save_cjshsj = save_cjshsj;
	}
	public String getSave_cjst() {
		return save_cjst;
	}
	public void setSave_cjst(String save_cjst) {
		this.save_cjst = save_cjst;
	}
	public String getSave_hsrhzw() {
		return save_hsrhzw;
	}
	public void setSave_hsrhzw(String save_hsrhzw) {
		this.save_hsrhzw = save_hsrhzw;
	}
	public String getSave_rtdd() {
		return save_rtdd;
	}
	public void setSave_rtdd(String save_rtdd) {
		this.save_rtdd = save_rtdd;
	}
	public String getSave_rtrq() {
		return save_rtrq;
	}
	public void setSave_rtrq(String save_rtrq) {
		this.save_rtrq = save_rtrq;
	}
	public String getSave_tjyd() {
		return save_tjyd;
	}
	public void setSave_tjyd(String save_tjyd) {
		this.save_tjyd = save_tjyd;
	}
	public String getSave_xh() {
		return save_xh;
	}
	public void setSave_xh(String save_xh) {
		this.save_xh = save_xh;
	}
	public String getSave_xydm() {
		return save_xydm;
	}
	public void setSave_xydm(String save_xydm) {
		this.save_xydm = save_xydm;
	}
	public String getSave_zydm() {
		return save_zydm;
	}
	public void setSave_zydm(String save_zydm) {
		this.save_zydm = save_zydm;
	}
	public String getSave_zyzqk() {
		return save_zyzqk;
	}
	public void setSave_zyzqk(String save_zyzqk) {
		this.save_zyzqk = save_zyzqk;
	}
	public String getTjyd() {
		return tjyd;
	}
	public void setTjyd(String tjyd) {
		this.tjyd = tjyd;
	}
	public String[] getXh() {
		return xh;
	}
	public void setXh(String xh[]) {
		this.xh = xh;
	}
	public String getXydm() {
		return xydm;
	}
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
	public String getZydm() {
		return zydm;
	}
	public void setZydm(String zydm) {
		this.zydm = zydm;
	}
	public String getZyzqk() {
		return zyzqk;
	}
	public void setZyzqk(String zyzqk) {
		this.zyzqk = zyzqk;
	}
	public Pages getPages() {
		return pages;
	}
	public void setPages(Pages pages) {
		this.pages = pages;
	}
	public String getQueryequals_bjdm() {
		return queryequals_bjdm;
	}
	public void setQueryequals_bjdm(String queryequals_bjdm) {
		this.queryequals_bjdm = queryequals_bjdm;
	}
	public String getQueryequals_nj() {
		return queryequals_nj;
	}
	public void setQueryequals_nj(String queryequals_nj) {
		this.queryequals_nj = queryequals_nj;
	}
	public String getQueryequals_xydm() {
		return queryequals_xydm;
	}
	public void setQueryequals_xydm(String queryequals_xydm) {
		this.queryequals_xydm = queryequals_xydm;
	}
	public String getQueryequals_zydm() {
		return queryequals_zydm;
	}
	public void setQueryequals_zydm(String queryequals_zydm) {
		this.queryequals_zydm = queryequals_zydm;
	}
	public String getQuerylike_xh() {
		return querylike_xh;
	}
	public void setQuerylike_xh(String querylike_xh) {
		this.querylike_xh = querylike_xh;
	}
	public String getQuerylike_xm() {
		return querylike_xm;
	}
	public void setQuerylike_xm(String querylike_xm) {
		this.querylike_xm = querylike_xm;
	}
	public String getQueryequals_sfyyd() {
		return queryequals_sfyyd;
	}
	public void setQueryequals_sfyyd(String queryequals_sfyyd) {
		this.queryequals_sfyyd = queryequals_sfyyd;
	}
	public String getSave_ydlx() {
		return save_ydlx;
	}
	public void setSave_ydlx(String save_ydlx) {
		this.save_ydlx = save_ydlx;
	}
	public String getSave_ydzt() {
		return save_ydzt;
	}
	public void setSave_ydzt(String save_ydzt) {
		this.save_ydzt = save_ydzt;
	}
	public String getBz() {
		return bz;
	}
	public void setBz(String bz) {
		this.bz = bz;
	}
	public String getSave_bz() {
		return save_bz;
	}
	public void setSave_bz(String save_bz) {
		this.save_bz = save_bz;
	}
	public String getXm() {
		return xm;
	}
	public void setXm(String xm) {
		this.xm = xm;
	}
	public String getXb() {
		return xb;
	}
	public void setXb(String xb) {
		this.xb = xb;
	}
	public String getNj() {
		return nj;
	}
	public void setNj(String nj) {
		this.nj = nj;
	}
	public String getBjmc() {
		return bjmc;
	}
	public void setBjmc(String bjmc) {
		this.bjmc = bjmc;
	}
	public String getXymc() {
		return xymc;
	}
	public void setXymc(String xymc) {
		this.xymc = xymc;
	}
	public String getZymc() {
		return zymc;
	}
	public void setZymc(String zymc) {
		this.zymc = zymc;
	}
	public String getSave_ydsj() {
		return save_ydsj;
	}
	public void setSave_ydsj(String save_ydsj) {
		this.save_ydsj = save_ydsj;
	}
	public String getSfzj() {
		return sfzj;
	}
	public void setSfzj(String sfzj) {
		this.sfzj = sfzj;
	}
	public String[] getCheckVal() {
		return checkVal;
	}
	public void setCheckVal(String[] checkVal) {
		this.checkVal = checkVal;
	}
	public String[] getPrimarykey_cbv() {
		return primarykey_cbv;
	}
	public void setPrimarykey_cbv(String[] primarykey_cbv) {
		this.primarykey_cbv = primarykey_cbv;
	}
	public String getQueryequals_ydlxmc() {
		return queryequals_ydlxmc;
	}
	public void setQueryequals_ydlxmc(String queryequals_ydlxmc) {
		this.queryequals_ydlxmc = queryequals_ydlxmc;
	}
	public String getQueryequals_ydzt() {
		return queryequals_ydzt;
	}
	public void setQueryequals_ydzt(String queryequals_ydzt) {
		this.queryequals_ydzt = queryequals_ydzt;
	}
	public String getQueryequals_checked() {
		return queryequals_checked;
	}
	public void setQueryequals_checked(String queryequals_checked) {
		this.queryequals_checked = queryequals_checked;
	}
}