/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package xgxt.xljk.mjxy.xlkh;

import org.apache.struts.action.ActionForm;

import xgxt.utils.Pages;

/** 
 * MyEclipse Struts
 * Creation date: 12-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="xljkMjxyKhxsftForm"
 */
public class XljkMjxyKhxsftForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String save_bh;
	private String save_ftsj;
	private String save_ftls;
	private String save_gzqk;
	private String save_zynr;
	private String save_ftjg;
	private String save_jbqk;
	private String save_txsj;
	
	private String querylike_ftls;
	private String querylike_bh;
	private String kssj;
	private String jssj;
	
	Pages pages=new Pages();
	public Pages getPages() {
		return pages;
	}
	public void setPages(Pages pages) {
		this.pages = pages;
	}
	public String getJssj() {
		return jssj;
	}
	public void setJssj(String jssj) {
		this.jssj = jssj;
	}
	public String getKssj() {
		return kssj;
	}
	public void setKssj(String kssj) {
		this.kssj = kssj;
	}
	public String getQuerylike_bh() {
		return querylike_bh;
	}
	public void setQuerylike_bh(String querylike_bh) {
		this.querylike_bh = querylike_bh;
	}
	public String getSave_bh() {
		return save_bh;
	}
	public void setSave_bh(String save_bh) {
		this.save_bh = save_bh;
	}
	public String getSave_ftjg() {
		return save_ftjg;
	}
	public void setSave_ftjg(String save_ftjg) {
		this.save_ftjg = save_ftjg;
	}
	public String getSave_ftls() {
		return save_ftls;
	}
	public void setSave_ftls(String save_ftls) {
		this.save_ftls = save_ftls;
	}
	public String getSave_ftsj() {
		return save_ftsj;
	}
	public void setSave_ftsj(String save_ftsj) {
		this.save_ftsj = save_ftsj;
	}
	public String getSave_gzqk() {
		return save_gzqk;
	}
	public void setSave_gzqk(String save_gzqk) {
		this.save_gzqk = save_gzqk;
	}
	public String getSave_jbqk() {
		return save_jbqk;
	}
	public void setSave_jbqk(String save_jbqk) {
		this.save_jbqk = save_jbqk;
	}
	public String getSave_txsj() {
		return save_txsj;
	}
	public void setSave_txsj(String save_txsj) {
		this.save_txsj = save_txsj;
	}
	public String getSave_zynr() {
		return save_zynr;
	}
	public void setSave_zynr(String save_zynr) {
		this.save_zynr = save_zynr;
	}
	public String getQuerylike_ftls() {
		return querylike_ftls;
	}
	public void setQuerylike_ftls(String querylike_ftls) {
		this.querylike_ftls = querylike_ftls;
	}
}